//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.23 at 09:10:05 AM UTC 
//


package ovl.schema.gccs;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ACLType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACLType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}START"/>
 *         &lt;element ref="{}END"/>
 *         &lt;element ref="{}ITEXT" minOccurs="0"/>
 *         &lt;element ref="{}OTEXT" minOccurs="0"/>
 *         &lt;element ref="{}LABEL" minOccurs="0"/>
 *         &lt;element name="VISIBLE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ACL_VIS_INT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AC_MIN_ALT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="AC_MAX_ALT" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="ELEVATION_UNITS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACLType", propOrder = {
    "start",
    "end",
    "itext",
    "otext",
    "label",
    "visible",
    "aclvisint",
    "acminalt",
    "acmaxalt",
    "elevationunits"
})
public class ACLType {

    @XmlElement(name = "START")
    protected int start;
    @XmlElement(name = "END")
    protected int end;
    @XmlElement(name = "ITEXT")
    protected String itext;
    @XmlElement(name = "OTEXT")
    protected String otext;
    @XmlElement(name = "LABEL", nillable = true)
    protected String label;
    @XmlElement(name = "VISIBLE")
    protected String visible;
    @XmlElement(name = "ACL_VIS_INT")
    protected Integer aclvisint;
    @XmlElement(name = "AC_MIN_ALT")
    protected BigDecimal acminalt;
    @XmlElement(name = "AC_MAX_ALT")
    protected BigDecimal acmaxalt;
    @XmlElement(name = "ELEVATION_UNITS")
    protected String elevationunits;

    /**
     * Gets the value of the start property.
     * 
     */
    public int getSTART() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     */
    public void setSTART(int value) {
        this.start = value;
    }

    /**
     * Gets the value of the end property.
     * 
     */
    public int getEND() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     */
    public void setEND(int value) {
        this.end = value;
    }

    /**
     * Gets the value of the itext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITEXT() {
        return itext;
    }

    /**
     * Sets the value of the itext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITEXT(String value) {
        this.itext = value;
    }

    /**
     * Gets the value of the otext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOTEXT() {
        return otext;
    }

    /**
     * Sets the value of the otext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOTEXT(String value) {
        this.otext = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLABEL() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLABEL(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVISIBLE() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVISIBLE(String value) {
        this.visible = value;
    }

    /**
     * Gets the value of the aclvisint property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getACLVISINT() {
        return aclvisint;
    }

    /**
     * Sets the value of the aclvisint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setACLVISINT(Integer value) {
        this.aclvisint = value;
    }

    /**
     * Gets the value of the acminalt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getACMINALT() {
        return acminalt;
    }

    /**
     * Sets the value of the acminalt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setACMINALT(BigDecimal value) {
        this.acminalt = value;
    }

    /**
     * Gets the value of the acmaxalt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getACMAXALT() {
        return acmaxalt;
    }

    /**
     * Sets the value of the acmaxalt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setACMAXALT(BigDecimal value) {
        this.acmaxalt = value;
    }

    /**
     * Gets the value of the elevationunits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getELEVATIONUNITS() {
        return elevationunits;
    }

    /**
     * Sets the value of the elevationunits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setELEVATIONUNITS(String value) {
        this.elevationunits = value;
    }

}
