//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.23 at 09:10:05 AM UTC 
//


package ovl.schema.gccs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ObjectGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NAME"/>
 *         &lt;element ref="{}DESCRIPTION" minOccurs="0"/>
 *         &lt;element ref="{}REMARKS" minOccurs="0"/>
 *         &lt;element ref="{}VISIBILITY" minOccurs="0"/>
 *         &lt;element ref="{}PRIORITY" minOccurs="0"/>
 *         &lt;element ref="{}BLINK" minOccurs="0"/>
 *         &lt;group ref="{}SingleObjects" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectGroup", propOrder = {
    "name",
    "description",
    "remarks",
    "visibility",
    "priority",
    "blink",
    "singleObjects"
})
public class ObjectGroup {

    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "DESCRIPTION")
    protected String description;
    @XmlElement(name = "REMARKS")
    protected String remarks;
    @XmlElement(name = "VISIBILITY", defaultValue = "true")
    protected Boolean visibility;
    @XmlElement(name = "PRIORITY", defaultValue = "50")
    protected Integer priority;
    @XmlElement(name = "BLINK", defaultValue = "false")
    protected Boolean blink;
    @XmlElements({
        @XmlElement(name = "circle", type = CircleType.class),
        @XmlElement(name = "text", type = TextType.class),
        @XmlElement(name = "arrow", type = ArrowType.class),
        @XmlElement(name = "box", type = BoxType.class),
        @XmlElement(name = "ellipse", type = EllipseType.class),
        @XmlElement(name = "arc", type = ArcType.class),
        @XmlElement(name = "polygon", type = PolygonType.class),
        @XmlElement(name = "rectangle", type = RectangleType.class),
        @XmlElement(name = "sector", type = SectorType.class),
        @XmlElement(name = "symbol", type = SymbolType.class),
        @XmlElement(name = "unit", type = UnitType.class),
        @XmlElement(name = "corridor", type = CorridorType.class),
        @XmlElement(name = "bitmap", type = BitmapType.class),
        @XmlElement(name = "tacsymbol", type = TacsymbolType.class),
        @XmlElement(name = "milbcorridor", type = MilbcorridorType.class),
        @XmlElement(name = "milbpolygon", type = MilbpolygonType.class),
        @XmlElement(name = "windarea", type = WindareaType.class),
        @XmlElement(name = "windbarb", type = WindbarbType.class),
        @XmlElement(name = "milbobject", type = MilbobjectType.class),
        @XmlElement(name = "boundary", type = BoundaryType.class),
        @XmlElement(name = "ellipticalarc", type = EllipticalArcType.class)
    })
    protected List<Object> singleObjects;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREMARKS() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREMARKS(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVISIBILITY() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVISIBILITY(Boolean value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPRIORITY() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPRIORITY(Integer value) {
        this.priority = value;
    }

    /**
     * Gets the value of the blink property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBLINK() {
        return blink;
    }

    /**
     * Sets the value of the blink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBLINK(Boolean value) {
        this.blink = value;
    }

    /**
     * Gets the value of the singleObjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the singleObjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSingleObjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CircleType }
     * {@link TextType }
     * {@link ArrowType }
     * {@link BoxType }
     * {@link EllipseType }
     * {@link ArcType }
     * {@link PolygonType }
     * {@link RectangleType }
     * {@link SectorType }
     * {@link SymbolType }
     * {@link UnitType }
     * {@link CorridorType }
     * {@link BitmapType }
     * {@link TacsymbolType }
     * {@link MilbcorridorType }
     * {@link MilbpolygonType }
     * {@link WindareaType }
     * {@link WindbarbType }
     * {@link MilbobjectType }
     * {@link BoundaryType }
     * {@link EllipticalArcType }
     * 
     * 
     */
    public List<Object> getSingleObjects() {
        if (singleObjects == null) {
            singleObjects = new ArrayList<Object>();
        }
        return this.singleObjects;
    }

}
