//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.23 at 09:10:17 AM UTC 
//


package ovl.schema.c2pc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ACPType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACPType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}POSITION"/>
 *         &lt;element ref="{}WIDTH"/>
 *         &lt;element ref="{}LABEL" minOccurs="0"/>
 *         &lt;element ref="{}VISIBLE" minOccurs="0"/>
 *         &lt;element name="AC_CONTROL_PT_UID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACPType", propOrder = {
    "position",
    "width",
    "label",
    "visible",
    "accontrolptuid"
})
public class ACPType {

    @XmlList
    @XmlElement(name = "POSITION", required = true)
    protected List<BigDecimal> position;
    @XmlElement(name = "WIDTH", required = true)
    protected BigDecimal width;
    @XmlElement(name = "LABEL", nillable = true)
    protected String label;
    @XmlElement(name = "VISIBLE", defaultValue = "true")
    protected String visible;
    @XmlElement(name = "AC_CONTROL_PT_UID")
    protected String accontrolptuid;

    /**
     * Gets the value of the position property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the position property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPOSITION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getPOSITION() {
        if (position == null) {
            position = new ArrayList<BigDecimal>();
        }
        return this.position;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWIDTH() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWIDTH(BigDecimal value) {
        this.width = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLABEL() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLABEL(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVISIBLE() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVISIBLE(String value) {
        this.visible = value;
    }

    /**
     * Gets the value of the accontrolptuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCONTROLPTUID() {
        return accontrolptuid;
    }

    /**
     * Sets the value of the accontrolptuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCONTROLPTUID(String value) {
        this.accontrolptuid = value;
    }

}
