//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.23 at 09:10:17 AM UTC 
//


package ovl.schema.c2pc;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for boxType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="boxType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MIL_ID" minOccurs="0"/>
 *         &lt;element ref="{}NAME" minOccurs="0"/>
 *         &lt;element ref="{}DESCRIPTION" minOccurs="0"/>
 *         &lt;element ref="{}REMARKS" minOccurs="0"/>
 *         &lt;element ref="{}MAX_SCALE" minOccurs="0"/>
 *         &lt;element ref="{}MIN_SCALE" minOccurs="0"/>
 *         &lt;element ref="{}SCALE_ACTIVATED" minOccurs="0"/>
 *         &lt;element ref="{}LABEL_TYPE" minOccurs="0"/>
 *         &lt;element ref="{}VISIBILITY" minOccurs="0"/>
 *         &lt;element ref="{}PRIORITY" minOccurs="0"/>
 *         &lt;element ref="{}LINE_COLOR" minOccurs="0"/>
 *         &lt;element ref="{}FILL_COLOR" minOccurs="0"/>
 *         &lt;element ref="{}FILL_TYPE" minOccurs="0"/>
 *         &lt;element ref="{}LINE_TYPE" minOccurs="0"/>
 *         &lt;element name="LINE_STYLE" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element ref="{}LINE_WIDTH" minOccurs="0"/>
 *         &lt;element ref="{}LINE_GEOM" minOccurs="0"/>
 *         &lt;element ref="{}BLINK" minOccurs="0"/>
 *         &lt;element name="SIZE" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element ref="{}URL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}C2PC_LINE_TYPE" minOccurs="0"/>
 *         &lt;element ref="{}SCALE_LINES" minOccurs="0"/>
 *         &lt;element ref="{}SCALE_LINES_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{}TEXT" minOccurs="0"/>
 *         &lt;element ref="{}TEXTCOLOR" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_EDGE_COLOR" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_BACKGROUND_COLOR" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_EDGE_SHOW" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_LABEL_SHOW" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_LABEL_SCALE" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_UNDERLINE" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_STRIKETHROUGH" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_HEIGHT" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_WIDTH" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_OFFSET_X" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_OFFSET_Y" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_ALIGNMENT" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_BACKGROUND_SHOW" minOccurs="0"/>
 *         &lt;element ref="{}FONT" minOccurs="0"/>
 *         &lt;element ref="{}METADATA" minOccurs="0"/>
 *         &lt;element ref="{}METADATA_TITLE" minOccurs="0"/>
 *         &lt;element ref="{}CUSTOM_INDEX" minOccurs="0"/>
 *         &lt;element ref="{}CUSTOM_TOOLTIP" minOccurs="0"/>
 *         &lt;element ref="{}ROTATION" minOccurs="0"/>
 *         &lt;element ref="{}AFFILIATION" minOccurs="0"/>
 *         &lt;element ref="{}URN" minOccurs="0"/>
 *         &lt;element ref="{}TACTICAL_DATA_TYPE" minOccurs="0"/>
 *         &lt;element ref="{}TIME_ALERT_ENABLED" minOccurs="0"/>
 *         &lt;element ref="{}TIME_ALERT_MSG" minOccurs="0"/>
 *         &lt;element ref="{}TIME_ALERT_DTG" minOccurs="0"/>
 *         &lt;element ref="{}BOUNDARY_ALERT_ENTER_ENABLED" minOccurs="0"/>
 *         &lt;element ref="{}START_DISPLAY_TIME" minOccurs="0"/>
 *         &lt;element ref="{}END_DISPLAY_TIME" minOccurs="0"/>
 *         &lt;element ref="{}ENABLE_ONOFF_BY_DTG" minOccurs="0"/>
 *         &lt;element ref="{}MODIFIED_TIME" minOccurs="0"/>
 *         &lt;element ref="{}CREATE_TIME" minOccurs="0"/>
 *         &lt;element ref="{}W" minOccurs="0"/>
 *         &lt;element ref="{}W1" minOccurs="0"/>
 *         &lt;element ref="{}SOURCE" minOccurs="0"/>
 *         &lt;element ref="{}CENTER"/>
 *         &lt;element ref="{}BEARING"/>
 *         &lt;element ref="{}LENGTH"/>
 *         &lt;element ref="{}WIDTH"/>
 *         &lt;element ref="{}ROUNDED_CORNERS" minOccurs="0"/>
 *         &lt;element ref="{}RADIUS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "boxType", propOrder = {
    "milid",
    "name",
    "description",
    "remarks",
    "maxscale",
    "minscale",
    "scaleactivated",
    "labeltype",
    "visibility",
    "priority",
    "linecolor",
    "fillcolor",
    "filltype",
    "linetype",
    "linestyle",
    "linewidth",
    "linegeom",
    "blink",
    "size",
    "url",
    "c2PCLINETYPE",
    "scalelines",
    "scalelinesreference",
    "text",
    "textcolor",
    "textedgecolor",
    "textbackgroundcolor",
    "textedgeshow",
    "textlabelshow",
    "textlabelscale",
    "textunderline",
    "textstrikethrough",
    "textheight",
    "textwidth",
    "textoffsetx",
    "textoffsety",
    "textalignment",
    "textbackgroundshow",
    "font",
    "metadata",
    "metadatatitle",
    "customindex",
    "customtooltip",
    "rotation",
    "affiliation",
    "urn",
    "tacticaldatatype",
    "timealertenabled",
    "timealertmsg",
    "timealertdtg",
    "boundaryalertenterenabled",
    "startdisplaytime",
    "enddisplaytime",
    "enableonoffbydtg",
    "modifiedtime",
    "createtime",
    "w",
    "w1",
    "source",
    "center",
    "bearing",
    "length",
    "width",
    "roundedcorners",
    "radius"
})
public class BoxType {

    @XmlElement(name = "MIL_ID")
    protected String milid;
    @XmlElement(name = "NAME")
    protected String name;
    @XmlElement(name = "DESCRIPTION")
    protected String description;
    @XmlElement(name = "REMARKS")
    protected String remarks;
    @XmlElement(name = "MAX_SCALE", defaultValue = "1")
    protected Integer maxscale;
    @XmlElement(name = "MIN_SCALE", defaultValue = "2147483647")
    protected Integer minscale;
    @XmlElement(name = "SCALE_ACTIVATED", defaultValue = "false")
    protected Boolean scaleactivated;
    @XmlElement(name = "LABEL_TYPE", defaultValue = "None")
    protected String labeltype;
    @XmlElement(name = "VISIBILITY", defaultValue = "true")
    protected Boolean visibility;
    @XmlElement(name = "PRIORITY", defaultValue = "50")
    protected Integer priority;
    @XmlElement(name = "LINE_COLOR", defaultValue = "255 255 0")
    protected String linecolor;
    @XmlElement(name = "FILL_COLOR", defaultValue = "0 0 0")
    protected String fillcolor;
    @XmlElement(name = "FILL_TYPE", defaultValue = "1")
    protected Integer filltype;
    @XmlElement(name = "LINE_TYPE", defaultValue = "0")
    protected BigInteger linetype;
    @XmlElement(name = "LINE_STYLE")
    protected Object linestyle;
    @XmlElement(name = "LINE_WIDTH", defaultValue = "1")
    protected BigInteger linewidth;
    @XmlElement(name = "LINE_GEOM", defaultValue = "1")
    protected BigInteger linegeom;
    @XmlElement(name = "BLINK", defaultValue = "false")
    protected Boolean blink;
    @XmlElement(name = "SIZE")
    protected Object size;
    @XmlElement(name = "URL")
    protected List<String> url;
    @XmlElement(name = "C2PC_LINE_TYPE")
    protected Long c2PCLINETYPE;
    @XmlElement(name = "SCALE_LINES")
    protected Long scalelines;
    @XmlElement(name = "SCALE_LINES_REFERENCE")
    protected Long scalelinesreference;
    @XmlElement(name = "TEXT")
    protected String text;
    @XmlElement(name = "TEXTCOLOR", defaultValue = "255 255 0")
    protected String textcolor;
    @XmlElement(name = "TEXT_EDGE_COLOR")
    protected String textedgecolor;
    @XmlElement(name = "TEXT_BACKGROUND_COLOR")
    protected String textbackgroundcolor;
    @XmlElement(name = "TEXT_EDGE_SHOW")
    protected Long textedgeshow;
    @XmlElement(name = "TEXT_LABEL_SHOW")
    protected Long textlabelshow;
    @XmlElement(name = "TEXT_LABEL_SCALE")
    protected Long textlabelscale;
    @XmlElement(name = "TEXT_UNDERLINE")
    protected Long textunderline;
    @XmlElement(name = "TEXT_STRIKETHROUGH")
    protected Long textstrikethrough;
    @XmlElement(name = "TEXT_HEIGHT")
    protected Long textheight;
    @XmlElement(name = "TEXT_WIDTH")
    protected Long textwidth;
    @XmlElement(name = "TEXT_OFFSET_X")
    protected Long textoffsetx;
    @XmlElement(name = "TEXT_OFFSET_Y")
    protected Long textoffsety;
    @XmlElement(name = "TEXT_ALIGNMENT")
    protected Long textalignment;
    @XmlElement(name = "TEXT_BACKGROUND_SHOW")
    protected Long textbackgroundshow;
    @XmlElement(name = "FONT", defaultValue = "Arial:3:12")
    protected String font;
    @XmlElement(name = "METADATA")
    protected String metadata;
    @XmlElement(name = "METADATA_TITLE")
    protected String metadatatitle;
    @XmlElement(name = "CUSTOM_INDEX")
    protected Long customindex;
    @XmlElement(name = "CUSTOM_TOOLTIP")
    protected String customtooltip;
    @XmlElement(name = "ROTATION")
    protected BigDecimal rotation;
    @XmlElement(name = "AFFILIATION")
    protected String affiliation;
    @XmlElement(name = "URN")
    protected String urn;
    @XmlElement(name = "TACTICAL_DATA_TYPE")
    protected String tacticaldatatype;
    @XmlElement(name = "TIME_ALERT_ENABLED")
    protected Boolean timealertenabled;
    @XmlElement(name = "TIME_ALERT_MSG")
    protected String timealertmsg;
    @XmlElement(name = "TIME_ALERT_DTG")
    protected Object timealertdtg;
    @XmlElement(name = "BOUNDARY_ALERT_ENTER_ENABLED")
    protected Boolean boundaryalertenterenabled;
    @XmlElement(name = "START_DISPLAY_TIME")
    protected Long startdisplaytime;
    @XmlElement(name = "END_DISPLAY_TIME")
    protected Long enddisplaytime;
    @XmlElement(name = "ENABLE_ONOFF_BY_DTG")
    protected Long enableonoffbydtg;
    @XmlElement(name = "MODIFIED_TIME")
    protected Integer modifiedtime;
    @XmlElement(name = "CREATE_TIME")
    protected Integer createtime;
    @XmlElement(name = "W", nillable = true)
    protected String w;
    @XmlElement(name = "W1", nillable = true)
    protected String w1;
    @XmlElement(name = "SOURCE")
    protected String source;
    @XmlList
    @XmlElement(name = "CENTER", required = true)
    protected List<BigDecimal> center;
    @XmlElement(name = "BEARING", required = true, defaultValue = "0.0")
    protected BigDecimal bearing;
    @XmlElement(name = "LENGTH", required = true)
    protected BigDecimal length;
    @XmlElement(name = "WIDTH", required = true)
    protected BigDecimal width;
    @XmlElement(name = "ROUNDED_CORNERS")
    protected Boolean roundedcorners;
    @XmlElement(name = "RADIUS")
    protected BigDecimal radius;

    /**
     * Gets the value of the milid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMILID() {
        return milid;
    }

    /**
     * Sets the value of the milid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMILID(String value) {
        this.milid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREMARKS() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREMARKS(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the maxscale property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMAXSCALE() {
        return maxscale;
    }

    /**
     * Sets the value of the maxscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMAXSCALE(Integer value) {
        this.maxscale = value;
    }

    /**
     * Gets the value of the minscale property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMINSCALE() {
        return minscale;
    }

    /**
     * Sets the value of the minscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMINSCALE(Integer value) {
        this.minscale = value;
    }

    /**
     * Gets the value of the scaleactivated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSCALEACTIVATED() {
        return scaleactivated;
    }

    /**
     * Sets the value of the scaleactivated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSCALEACTIVATED(Boolean value) {
        this.scaleactivated = value;
    }

    /**
     * Gets the value of the labeltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLABELTYPE() {
        return labeltype;
    }

    /**
     * Sets the value of the labeltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLABELTYPE(String value) {
        this.labeltype = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVISIBILITY() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVISIBILITY(Boolean value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPRIORITY() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPRIORITY(Integer value) {
        this.priority = value;
    }

    /**
     * Gets the value of the linecolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLINECOLOR() {
        return linecolor;
    }

    /**
     * Sets the value of the linecolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLINECOLOR(String value) {
        this.linecolor = value;
    }

    /**
     * Gets the value of the fillcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFILLCOLOR() {
        return fillcolor;
    }

    /**
     * Sets the value of the fillcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFILLCOLOR(String value) {
        this.fillcolor = value;
    }

    /**
     * Gets the value of the filltype property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFILLTYPE() {
        return filltype;
    }

    /**
     * Sets the value of the filltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFILLTYPE(Integer value) {
        this.filltype = value;
    }

    /**
     * Gets the value of the linetype property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLINETYPE() {
        return linetype;
    }

    /**
     * Sets the value of the linetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLINETYPE(BigInteger value) {
        this.linetype = value;
    }

    /**
     * Gets the value of the linestyle property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLINESTYLE() {
        return linestyle;
    }

    /**
     * Sets the value of the linestyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLINESTYLE(Object value) {
        this.linestyle = value;
    }

    /**
     * Gets the value of the linewidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLINEWIDTH() {
        return linewidth;
    }

    /**
     * Sets the value of the linewidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLINEWIDTH(BigInteger value) {
        this.linewidth = value;
    }

    /**
     * Gets the value of the linegeom property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLINEGEOM() {
        return linegeom;
    }

    /**
     * Sets the value of the linegeom property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLINEGEOM(BigInteger value) {
        this.linegeom = value;
    }

    /**
     * Gets the value of the blink property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBLINK() {
        return blink;
    }

    /**
     * Sets the value of the blink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBLINK(Boolean value) {
        this.blink = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSIZE() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSIZE(Object value) {
        this.size = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the url property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getURL() {
        if (url == null) {
            url = new ArrayList<String>();
        }
        return this.url;
    }

    /**
     * Gets the value of the c2PCLINETYPE property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getC2PCLINETYPE() {
        return c2PCLINETYPE;
    }

    /**
     * Sets the value of the c2PCLINETYPE property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setC2PCLINETYPE(Long value) {
        this.c2PCLINETYPE = value;
    }

    /**
     * Gets the value of the scalelines property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSCALELINES() {
        return scalelines;
    }

    /**
     * Sets the value of the scalelines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSCALELINES(Long value) {
        this.scalelines = value;
    }

    /**
     * Gets the value of the scalelinesreference property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSCALELINESREFERENCE() {
        return scalelinesreference;
    }

    /**
     * Sets the value of the scalelinesreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSCALELINESREFERENCE(Long value) {
        this.scalelinesreference = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXT() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXT(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the textcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXTCOLOR() {
        return textcolor;
    }

    /**
     * Sets the value of the textcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXTCOLOR(String value) {
        this.textcolor = value;
    }

    /**
     * Gets the value of the textedgecolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXTEDGECOLOR() {
        return textedgecolor;
    }

    /**
     * Sets the value of the textedgecolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXTEDGECOLOR(String value) {
        this.textedgecolor = value;
    }

    /**
     * Gets the value of the textbackgroundcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXTBACKGROUNDCOLOR() {
        return textbackgroundcolor;
    }

    /**
     * Sets the value of the textbackgroundcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXTBACKGROUNDCOLOR(String value) {
        this.textbackgroundcolor = value;
    }

    /**
     * Gets the value of the textedgeshow property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTEDGESHOW() {
        return textedgeshow;
    }

    /**
     * Sets the value of the textedgeshow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTEDGESHOW(Long value) {
        this.textedgeshow = value;
    }

    /**
     * Gets the value of the textlabelshow property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTLABELSHOW() {
        return textlabelshow;
    }

    /**
     * Sets the value of the textlabelshow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTLABELSHOW(Long value) {
        this.textlabelshow = value;
    }

    /**
     * Gets the value of the textlabelscale property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTLABELSCALE() {
        return textlabelscale;
    }

    /**
     * Sets the value of the textlabelscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTLABELSCALE(Long value) {
        this.textlabelscale = value;
    }

    /**
     * Gets the value of the textunderline property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTUNDERLINE() {
        return textunderline;
    }

    /**
     * Sets the value of the textunderline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTUNDERLINE(Long value) {
        this.textunderline = value;
    }

    /**
     * Gets the value of the textstrikethrough property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTSTRIKETHROUGH() {
        return textstrikethrough;
    }

    /**
     * Sets the value of the textstrikethrough property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTSTRIKETHROUGH(Long value) {
        this.textstrikethrough = value;
    }

    /**
     * Gets the value of the textheight property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTHEIGHT() {
        return textheight;
    }

    /**
     * Sets the value of the textheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTHEIGHT(Long value) {
        this.textheight = value;
    }

    /**
     * Gets the value of the textwidth property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTWIDTH() {
        return textwidth;
    }

    /**
     * Sets the value of the textwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTWIDTH(Long value) {
        this.textwidth = value;
    }

    /**
     * Gets the value of the textoffsetx property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTOFFSETX() {
        return textoffsetx;
    }

    /**
     * Sets the value of the textoffsetx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTOFFSETX(Long value) {
        this.textoffsetx = value;
    }

    /**
     * Gets the value of the textoffsety property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTOFFSETY() {
        return textoffsety;
    }

    /**
     * Sets the value of the textoffsety property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTOFFSETY(Long value) {
        this.textoffsety = value;
    }

    /**
     * Gets the value of the textalignment property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTALIGNMENT() {
        return textalignment;
    }

    /**
     * Sets the value of the textalignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTALIGNMENT(Long value) {
        this.textalignment = value;
    }

    /**
     * Gets the value of the textbackgroundshow property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTBACKGROUNDSHOW() {
        return textbackgroundshow;
    }

    /**
     * Sets the value of the textbackgroundshow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTBACKGROUNDSHOW(Long value) {
        this.textbackgroundshow = value;
    }

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFONT() {
        return font;
    }

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFONT(String value) {
        this.font = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMETADATA() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMETADATA(String value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the metadatatitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMETADATATITLE() {
        return metadatatitle;
    }

    /**
     * Sets the value of the metadatatitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMETADATATITLE(String value) {
        this.metadatatitle = value;
    }

    /**
     * Gets the value of the customindex property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCUSTOMINDEX() {
        return customindex;
    }

    /**
     * Sets the value of the customindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCUSTOMINDEX(Long value) {
        this.customindex = value;
    }

    /**
     * Gets the value of the customtooltip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTOMTOOLTIP() {
        return customtooltip;
    }

    /**
     * Sets the value of the customtooltip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTOMTOOLTIP(String value) {
        this.customtooltip = value;
    }

    /**
     * Gets the value of the rotation property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getROTATION() {
        return rotation;
    }

    /**
     * Sets the value of the rotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setROTATION(BigDecimal value) {
        this.rotation = value;
    }

    /**
     * Gets the value of the affiliation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAFFILIATION() {
        return affiliation;
    }

    /**
     * Sets the value of the affiliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAFFILIATION(String value) {
        this.affiliation = value;
    }

    /**
     * Gets the value of the urn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURN() {
        return urn;
    }

    /**
     * Sets the value of the urn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURN(String value) {
        this.urn = value;
    }

    /**
     * Gets the value of the tacticaldatatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTACTICALDATATYPE() {
        return tacticaldatatype;
    }

    /**
     * Sets the value of the tacticaldatatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTACTICALDATATYPE(String value) {
        this.tacticaldatatype = value;
    }

    /**
     * Gets the value of the timealertenabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTIMEALERTENABLED() {
        return timealertenabled;
    }

    /**
     * Sets the value of the timealertenabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTIMEALERTENABLED(Boolean value) {
        this.timealertenabled = value;
    }

    /**
     * Gets the value of the timealertmsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMEALERTMSG() {
        return timealertmsg;
    }

    /**
     * Sets the value of the timealertmsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMEALERTMSG(String value) {
        this.timealertmsg = value;
    }

    /**
     * Gets the value of the timealertdtg property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTIMEALERTDTG() {
        return timealertdtg;
    }

    /**
     * Sets the value of the timealertdtg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTIMEALERTDTG(Object value) {
        this.timealertdtg = value;
    }

    /**
     * Gets the value of the boundaryalertenterenabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBOUNDARYALERTENTERENABLED() {
        return boundaryalertenterenabled;
    }

    /**
     * Sets the value of the boundaryalertenterenabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBOUNDARYALERTENTERENABLED(Boolean value) {
        this.boundaryalertenterenabled = value;
    }

    /**
     * Gets the value of the startdisplaytime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSTARTDISPLAYTIME() {
        return startdisplaytime;
    }

    /**
     * Sets the value of the startdisplaytime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSTARTDISPLAYTIME(Long value) {
        this.startdisplaytime = value;
    }

    /**
     * Gets the value of the enddisplaytime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getENDDISPLAYTIME() {
        return enddisplaytime;
    }

    /**
     * Sets the value of the enddisplaytime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setENDDISPLAYTIME(Long value) {
        this.enddisplaytime = value;
    }

    /**
     * Gets the value of the enableonoffbydtg property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getENABLEONOFFBYDTG() {
        return enableonoffbydtg;
    }

    /**
     * Sets the value of the enableonoffbydtg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setENABLEONOFFBYDTG(Long value) {
        this.enableonoffbydtg = value;
    }

    /**
     * Gets the value of the modifiedtime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMODIFIEDTIME() {
        return modifiedtime;
    }

    /**
     * Sets the value of the modifiedtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMODIFIEDTIME(Integer value) {
        this.modifiedtime = value;
    }

    /**
     * Gets the value of the createtime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCREATETIME() {
        return createtime;
    }

    /**
     * Sets the value of the createtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCREATETIME(Integer value) {
        this.createtime = value;
    }

    /**
     * Gets the value of the w property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getW() {
        return w;
    }

    /**
     * Sets the value of the w property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setW(String value) {
        this.w = value;
    }

    /**
     * Gets the value of the w1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getW1() {
        return w1;
    }

    /**
     * Sets the value of the w1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setW1(String value) {
        this.w1 = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOURCE() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOURCE(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the center property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the center property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCENTER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getCENTER() {
        if (center == null) {
            center = new ArrayList<BigDecimal>();
        }
        return this.center;
    }

    /**
     * Gets the value of the bearing property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBEARING() {
        return bearing;
    }

    /**
     * Sets the value of the bearing property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBEARING(BigDecimal value) {
        this.bearing = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLENGTH() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLENGTH(BigDecimal value) {
        this.length = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWIDTH() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWIDTH(BigDecimal value) {
        this.width = value;
    }

    /**
     * Gets the value of the roundedcorners property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isROUNDEDCORNERS() {
        return roundedcorners;
    }

    /**
     * Sets the value of the roundedcorners property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setROUNDEDCORNERS(Boolean value) {
        this.roundedcorners = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRADIUS() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRADIUS(BigDecimal value) {
        this.radius = value;
    }

}
