//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.23 at 09:10:17 AM UTC 
//


package ovl.schema.c2pc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{}PlottableObjects" maxOccurs="unbounded"/>
 *         &lt;element ref="{}REFERENCE_POINT" minOccurs="0"/>
 *         &lt;element ref="{}MAP_WIDTH" minOccurs="0"/>
 *         &lt;element ref="{}MAP_CENTER" minOccurs="0"/>
 *         &lt;element ref="{}CREATE_TIME" minOccurs="0"/>
 *         &lt;element ref="{}START_TIME" minOccurs="0"/>
 *         &lt;element ref="{}MODIFIED_TIME" minOccurs="0"/>
 *         &lt;element ref="{}END_TIME" minOccurs="0"/>
 *         &lt;element ref="{}MIN_SCALE" minOccurs="0"/>
 *         &lt;element ref="{}MAX_SCALE" minOccurs="0"/>
 *         &lt;element ref="{}NAME"/>
 *         &lt;element ref="{}SOURCE" minOccurs="0"/>
 *         &lt;element ref="{}URN" minOccurs="0"/>
 *         &lt;element ref="{}READ_ONLY" minOccurs="0"/>
 *         &lt;element ref="{}DESCRIPTION" minOccurs="0"/>
 *         &lt;element ref="{}REMARKS" minOccurs="0"/>
 *         &lt;element ref="{}VMF_TYPE" minOccurs="0"/>
 *         &lt;element name="LAYERS" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "plottableObjects",
    "referencepoint",
    "mapwidth",
    "mapcenter",
    "createtime",
    "starttime",
    "modifiedtime",
    "endtime",
    "minscale",
    "maxscale",
    "name",
    "source",
    "urn",
    "readonly",
    "description",
    "remarks",
    "vmftype",
    "layers"
})
@XmlRootElement(name = "MODEL")
public class MODEL {

    @XmlElements({
        @XmlElement(name = "circle", type = CircleType.class),
        @XmlElement(name = "c2pcimage", type = C2PCimageType.class),
        @XmlElement(name = "c2pcoleobject", type = C2PcoleobjectType.class),
        @XmlElement(name = "text", type = TextType.class),
        @XmlElement(name = "arrow", type = ArrowType.class),
        @XmlElement(name = "box", type = BoxType.class),
        @XmlElement(name = "ellipse", type = EllipseType.class),
        @XmlElement(name = "arc", type = ArcType.class),
        @XmlElement(name = "polygon", type = PolygonType.class),
        @XmlElement(name = "rectangle", type = RectangleType.class),
        @XmlElement(name = "sector", type = SectorType.class),
        @XmlElement(name = "symbol", type = SymbolType.class),
        @XmlElement(name = "unit", type = UnitType.class),
        @XmlElement(name = "corridor", type = CorridorType.class),
        @XmlElement(name = "bitmap", type = BitmapType.class),
        @XmlElement(name = "tacsymbol", type = TacsymbolType.class),
        @XmlElement(name = "milbcorridor", type = MilbcorridorType.class),
        @XmlElement(name = "milbobject", type = MilbobjectType.class),
        @XmlElement(name = "boundary", type = BoundaryType.class),
        @XmlElement(name = "group", type = GroupType.class)
    })
    protected List<Object> plottableObjects;
    @XmlList
    @XmlElement(name = "REFERENCE_POINT", defaultValue = "0.0 0.0")
    protected List<BigDecimal> referencepoint;
    @XmlElement(name = "MAP_WIDTH")
    protected BigDecimal mapwidth;
    @XmlList
    @XmlElement(name = "MAP_CENTER", defaultValue = "0.0 0.0")
    protected List<BigDecimal> mapcenter;
    @XmlElement(name = "CREATE_TIME")
    protected Integer createtime;
    @XmlElement(name = "START_TIME")
    protected Integer starttime;
    @XmlElement(name = "MODIFIED_TIME")
    protected Integer modifiedtime;
    @XmlElement(name = "END_TIME")
    protected Integer endtime;
    @XmlElement(name = "MIN_SCALE", defaultValue = "2147483647")
    protected Integer minscale;
    @XmlElement(name = "MAX_SCALE", defaultValue = "1")
    protected Integer maxscale;
    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "SOURCE")
    protected String source;
    @XmlElement(name = "URN")
    protected String urn;
    @XmlElement(name = "READ_ONLY", defaultValue = "false")
    protected Boolean readonly;
    @XmlElement(name = "DESCRIPTION")
    protected String description;
    @XmlElement(name = "REMARKS")
    protected String remarks;
    @XmlElement(name = "VMF_TYPE")
    protected String vmftype;
    @XmlElement(name = "LAYERS")
    protected Long layers;

    /**
     * Gets the value of the plottableObjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plottableObjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlottableObjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CircleType }
     * {@link C2PCimageType }
     * {@link C2PcoleobjectType }
     * {@link TextType }
     * {@link ArrowType }
     * {@link BoxType }
     * {@link EllipseType }
     * {@link ArcType }
     * {@link PolygonType }
     * {@link RectangleType }
     * {@link SectorType }
     * {@link SymbolType }
     * {@link UnitType }
     * {@link CorridorType }
     * {@link BitmapType }
     * {@link TacsymbolType }
     * {@link MilbcorridorType }
     * {@link MilbobjectType }
     * {@link BoundaryType }
     * {@link GroupType }
     * 
     * 
     */
    public List<Object> getPlottableObjects() {
        if (plottableObjects == null) {
            plottableObjects = new ArrayList<Object>();
        }
        return this.plottableObjects;
    }

    /**
     * Gets the value of the referencepoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referencepoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getREFERENCEPOINT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getREFERENCEPOINT() {
        if (referencepoint == null) {
            referencepoint = new ArrayList<BigDecimal>();
        }
        return this.referencepoint;
    }

    /**
     * Gets the value of the mapwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMAPWIDTH() {
        return mapwidth;
    }

    /**
     * Sets the value of the mapwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMAPWIDTH(BigDecimal value) {
        this.mapwidth = value;
    }

    /**
     * Gets the value of the mapcenter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mapcenter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMAPCENTER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getMAPCENTER() {
        if (mapcenter == null) {
            mapcenter = new ArrayList<BigDecimal>();
        }
        return this.mapcenter;
    }

    /**
     * Gets the value of the createtime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCREATETIME() {
        return createtime;
    }

    /**
     * Sets the value of the createtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCREATETIME(Integer value) {
        this.createtime = value;
    }

    /**
     * Gets the value of the starttime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSTARTTIME() {
        return starttime;
    }

    /**
     * Sets the value of the starttime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSTARTTIME(Integer value) {
        this.starttime = value;
    }

    /**
     * Gets the value of the modifiedtime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMODIFIEDTIME() {
        return modifiedtime;
    }

    /**
     * Sets the value of the modifiedtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMODIFIEDTIME(Integer value) {
        this.modifiedtime = value;
    }

    /**
     * Gets the value of the endtime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getENDTIME() {
        return endtime;
    }

    /**
     * Sets the value of the endtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setENDTIME(Integer value) {
        this.endtime = value;
    }

    /**
     * Gets the value of the minscale property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMINSCALE() {
        return minscale;
    }

    /**
     * Sets the value of the minscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMINSCALE(Integer value) {
        this.minscale = value;
    }

    /**
     * Gets the value of the maxscale property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMAXSCALE() {
        return maxscale;
    }

    /**
     * Sets the value of the maxscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMAXSCALE(Integer value) {
        this.maxscale = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOURCE() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOURCE(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the urn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURN() {
        return urn;
    }

    /**
     * Sets the value of the urn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURN(String value) {
        this.urn = value;
    }

    /**
     * Gets the value of the readonly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isREADONLY() {
        return readonly;
    }

    /**
     * Sets the value of the readonly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setREADONLY(Boolean value) {
        this.readonly = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREMARKS() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREMARKS(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the vmftype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVMFTYPE() {
        return vmftype;
    }

    /**
     * Sets the value of the vmftype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVMFTYPE(String value) {
        this.vmftype = value;
    }

    /**
     * Gets the value of the layers property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLAYERS() {
        return layers;
    }

    /**
     * Sets the value of the layers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLAYERS(Long value) {
        this.layers = value;
    }

}
