//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.23 at 09:10:17 AM UTC 
//


package ovl.schema.c2pc;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ovl.schema.c2pc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TEXTOFFSETY_QNAME = new QName("", "TEXT_OFFSET_Y");
    private final static QName _KVIS_QNAME = new QName("", "K_VIS");
    private final static QName _TEXTOFFSETX_QNAME = new QName("", "TEXT_OFFSET_X");
    private final static QName _H1VIS_QNAME = new QName("", "H1_VIS");
    private final static QName _W1_QNAME = new QName("", "W1");
    private final static QName _CREATETIME_QNAME = new QName("", "CREATE_TIME");
    private final static QName _REFERENCEPOINT_QNAME = new QName("", "REFERENCE_POINT");
    private final static QName _SVIS_QNAME = new QName("", "S_VIS");
    private final static QName _ROW_QNAME = new QName("", "ROW");
    private final static QName _HVIS_QNAME = new QName("", "H_VIS");
    private final static QName _QVIS_QNAME = new QName("", "Q_VIS");
    private final static QName _STARTDISPLAYTIME_QNAME = new QName("", "START_DISPLAY_TIME");
    private final static QName _SEMIMAJOR_QNAME = new QName("", "SEMI_MAJOR");
    private final static QName _ROLEICONVIS_QNAME = new QName("", "ROLE_ICON_VIS");
    private final static QName _LVIS_QNAME = new QName("", "L_VIS");
    private final static QName _CUSTOMTOOLTIP_QNAME = new QName("", "CUSTOM_TOOLTIP");
    private final static QName _LINESTYLE_QNAME = new QName("", "LINE_STYLE");
    private final static QName _CENTER_QNAME = new QName("", "CENTER");
    private final static QName _AUTOOFFTOGGLE_QNAME = new QName("", "AUTO_OFF_TOGGLE");
    private final static QName _ENDBEARING_QNAME = new QName("", "ENDBEARING");
    private final static QName _NAME_QNAME = new QName("", "NAME");
    private final static QName _DESCRIPTION_QNAME = new QName("", "DESCRIPTION");
    private final static QName _OUTERRADIUS_QNAME = new QName("", "OUTER_RADIUS");
    private final static QName _INSERT_QNAME = new QName("", "INSERT");
    private final static QName _SCALELINESREFERENCE_QNAME = new QName("", "SCALE_LINES_REFERENCE");
    private final static QName _METADATATITLE_QNAME = new QName("", "METADATA_TITLE");
    private final static QName _STARTTIME_QNAME = new QName("", "START_TIME");
    private final static QName _TACTICALDATATYPE_QNAME = new QName("", "TACTICAL_DATA_TYPE");
    private final static QName _WVIS_QNAME = new QName("", "W_VIS");
    private final static QName _TEXTLABELSHOW_QNAME = new QName("", "TEXT_LABEL_SHOW");
    private final static QName _FRAMEFILLVIS_QNAME = new QName("", "FRAME_FILL_VIS");
    private final static QName _SYMBOLSIZE_QNAME = new QName("", "SYMBOL_SIZE");
    private final static QName _TVIS_QNAME = new QName("", "T_VIS");
    private final static QName _CVIS_QNAME = new QName("", "C_VIS");
    private final static QName _FONT_QNAME = new QName("", "FONT");
    private final static QName _TIMEALERTMSG_QNAME = new QName("", "TIME_ALERT_MSG");
    private final static QName _MAPCENTER_QNAME = new QName("", "MAP_CENTER");
    private final static QName _ACDISPLAYMASK_QNAME = new QName("", "AC_DISPLAY_MASK");
    private final static QName _MILID_QNAME = new QName("", "MIL_ID");
    private final static QName _LINETYPE_QNAME = new QName("", "LINE_TYPE");
    private final static QName _OLEDATA_QNAME = new QName("", "OLEDATA");
    private final static QName _READONLY_QNAME = new QName("", "READ_ONLY");
    private final static QName _F_QNAME = new QName("", "F");
    private final static QName _T1VIS_QNAME = new QName("", "T1_VIS");
    private final static QName _W1VIS_QNAME = new QName("", "W1_VIS");
    private final static QName _OUTERTEXT_QNAME = new QName("", "OUTER_TEXT");
    private final static QName _G_QNAME = new QName("", "G");
    private final static QName _URN_QNAME = new QName("", "URN");
    private final static QName _TEXTEDGECOLOR_QNAME = new QName("", "TEXT_EDGE_COLOR");
    private final static QName _VISIBILITY_QNAME = new QName("", "VISIBILITY");
    private final static QName _C_QNAME = new QName("", "C");
    private final static QName _HEIGHT_QNAME = new QName("", "HEIGHT");
    private final static QName _L_QNAME = new QName("", "L");
    private final static QName _M_QNAME = new QName("", "M");
    private final static QName _TIMEALERTENABLED_QNAME = new QName("", "TIME_ALERT_ENABLED");
    private final static QName _VMFTYPE_QNAME = new QName("", "VMF_TYPE");
    private final static QName _N_QNAME = new QName("", "N");
    private final static QName _H_QNAME = new QName("", "H");
    private final static QName _J_QNAME = new QName("", "J");
    private final static QName _NVIS_QNAME = new QName("", "N_VIS");
    private final static QName _ITEXT_QNAME = new QName("", "ITEXT");
    private final static QName _K_QNAME = new QName("", "K");
    private final static QName _STARTBEARING_QNAME = new QName("", "STARTBEARING");
    private final static QName _T_QNAME = new QName("", "T");
    private final static QName _W_QNAME = new QName("", "W");
    private final static QName _TEXTSTRIKETHROUGH_QNAME = new QName("", "TEXT_STRIKETHROUGH");
    private final static QName _CROSSED_QNAME = new QName("", "CROSSED");
    private final static QName _OPTFRAMEVIS_QNAME = new QName("", "OPT_FRAME_VIS");
    private final static QName _V_QNAME = new QName("", "V");
    private final static QName _SPDLDRVIS_QNAME = new QName("", "SPD_LDR_VIS");
    private final static QName _Q_QNAME = new QName("", "Q");
    private final static QName _P_QNAME = new QName("", "P");
    private final static QName _MINSCALE_QNAME = new QName("", "MIN_SCALE");
    private final static QName _Y_QNAME = new QName("", "Y");
    private final static QName _URL_QNAME = new QName("", "URL");
    private final static QName _X_QNAME = new QName("", "X");
    private final static QName _Z_QNAME = new QName("", "Z");
    private final static QName _TIMEALERTDTG_QNAME = new QName("", "TIME_ALERT_DTG");
    private final static QName _FILLTYPE_QNAME = new QName("", "FILL_TYPE");
    private final static QName _INNERRADIUS_QNAME = new QName("", "INNER_RADIUS");
    private final static QName _JVIS_QNAME = new QName("", "J_VIS");
    private final static QName _PRIORITY_QNAME = new QName("", "PRIORITY");
    private final static QName _BOUNDARYALERTENTERENABLED_QNAME = new QName("", "BOUNDARY_ALERT_ENTER_ENABLED");
    private final static QName _INNERTEXT_QNAME = new QName("", "INNER_TEXT");
    private final static QName _BEARING_QNAME = new QName("", "BEARING");
    private final static QName _WIDTH_QNAME = new QName("", "WIDTH");
    private final static QName _DVIS_QNAME = new QName("", "D_VIS");
    private final static QName _SCALELINES_QNAME = new QName("", "SCALE_LINES");
    private final static QName _TEXTBACKGROUNDSHOW_QNAME = new QName("", "TEXT_BACKGROUND_SHOW");
    private final static QName _TEXTCOLOR_QNAME = new QName("", "TEXTCOLOR");
    private final static QName _FVIS_QNAME = new QName("", "F_VIS");
    private final static QName _CLOSED_QNAME = new QName("", "CLOSED");
    private final static QName _H1_QNAME = new QName("", "H1");
    private final static QName _ABVIS_QNAME = new QName("", "AB_VIS");
    private final static QName _END_QNAME = new QName("", "END");
    private final static QName _SIZE_QNAME = new QName("", "SIZE");
    private final static QName _RADIUS_QNAME = new QName("", "RADIUS");
    private final static QName _PVIS_QNAME = new QName("", "P_VIS");
    private final static QName _OUTERTEXTVIS_QNAME = new QName("", "OUTER_TEXT_VIS");
    private final static QName _CUSTOMINDEX_QNAME = new QName("", "CUSTOM_INDEX");
    private final static QName _EVIS_QNAME = new QName("", "E_VIS");
    private final static QName _OTEXT_QNAME = new QName("", "OTEXT");
    private final static QName _GVIS_QNAME = new QName("", "G_VIS");
    private final static QName _OLEIMAGETYPE_QNAME = new QName("", "OLE_IMAGE_TYPE");
    private final static QName _INNERTEXTVIS_QNAME = new QName("", "INNER_TEXT_VIS");
    private final static QName _TEXTUNDERLINE_QNAME = new QName("", "TEXT_UNDERLINE");
    private final static QName _TEXTWIDTH_QNAME = new QName("", "TEXT_WIDTH");
    private final static QName _OLEDATASIZE_QNAME = new QName("", "OLE_DATA_SIZE");
    private final static QName _SOURCE_QNAME = new QName("", "SOURCE");
    private final static QName _CATTHREAT_QNAME = new QName("", "CAT_THREAT");
    private final static QName _INSERTSIZE_QNAME = new QName("", "INSERT_SIZE");
    private final static QName _RIGHTBEARING_QNAME = new QName("", "RIGHT_BEARING");
    private final static QName _ENDDISPLAYTIME_QNAME = new QName("", "END_DISPLAY_TIME");
    private final static QName _TEXTEDGESHOW_QNAME = new QName("", "TEXT_EDGE_SHOW");
    private final static QName _OLECLSID_QNAME = new QName("", "OLE_CLSID");
    private final static QName _POSITION_QNAME = new QName("", "POSITION");
    private final static QName _MAXSCALE_QNAME = new QName("", "MAX_SCALE");
    private final static QName _LENGTH_QNAME = new QName("", "LENGTH");
    private final static QName _ORG_QNAME = new QName("", "ORG");
    private final static QName _LABELTYPE_QNAME = new QName("", "LABEL_TYPE");
    private final static QName _POINT2_QNAME = new QName("", "POINT2");
    private final static QName _OLEIMAGEDATA_QNAME = new QName("", "OLE_IMAGE_DATA");
    private final static QName _POINT1_QNAME = new QName("", "POINT1");
    private final static QName _AAVIS_QNAME = new QName("", "AA_VIS");
    private final static QName _ROUNDEDCORNERS_QNAME = new QName("", "ROUNDED_CORNERS");
    private final static QName _AA_QNAME = new QName("", "AA");
    private final static QName _TEXTLABELSCALE_QNAME = new QName("", "TEXT_LABEL_SCALE");
    private final static QName _IMAGEFILE_QNAME = new QName("", "IMAGE_FILE");
    private final static QName _MAPWIDTH_QNAME = new QName("", "MAP_WIDTH");
    private final static QName _SEMIMINOR_QNAME = new QName("", "SEMI_MINOR");
    private final static QName _AFFILIATION_QNAME = new QName("", "AFFILIATION");
    private final static QName _LINECOLOR_QNAME = new QName("", "LINE_COLOR");
    private final static QName _REMARKS_QNAME = new QName("", "REMARKS");
    private final static QName _XVIS_QNAME = new QName("", "X_VIS");
    private final static QName _TEXTHEIGHT_QNAME = new QName("", "TEXT_HEIGHT");
    private final static QName _ROTATION_QNAME = new QName("", "ROTATION");
    private final static QName _TEXTALIGNMENT_QNAME = new QName("", "TEXT_ALIGNMENT");
    private final static QName _LINEGEOM_QNAME = new QName("", "LINE_GEOM");
    private final static QName _FILLCOLOR_QNAME = new QName("", "FILL_COLOR");
    private final static QName _IMAGETRANSPARENCY_QNAME = new QName("", "IMAGE_TRANSPARENCY");
    private final static QName _VISIBLE_QNAME = new QName("", "VISIBLE");
    private final static QName _MODIFIEDTIME_QNAME = new QName("", "MODIFIED_TIME");
    private final static QName _REPRESENTATION_QNAME = new QName("", "REPRESENTATION");
    private final static QName _TEXTBACKGROUNDCOLOR_QNAME = new QName("", "TEXT_BACKGROUND_COLOR");
    private final static QName _THREAT_QNAME = new QName("", "THREAT");
    private final static QName _ECHELON_QNAME = new QName("", "ECHELON");
    private final static QName _TEXT_QNAME = new QName("", "TEXT");
    private final static QName _ZVIS_QNAME = new QName("", "Z_VIS");
    private final static QName _SCALEACTIVATED_QNAME = new QName("", "SCALE_ACTIVATED");
    private final static QName _LINEWIDTH_QNAME = new QName("", "LINE_WIDTH");
    private final static QName _LEFTBEARING_QNAME = new QName("", "LEFT_BEARING");
    private final static QName _VVIS_QNAME = new QName("", "V_VIS");
    private final static QName _LABEL_QNAME = new QName("", "LABEL");
    private final static QName _ENABLEONOFFBYDTG_QNAME = new QName("", "ENABLE_ONOFF_BY_DTG");
    private final static QName _YVIS_QNAME = new QName("", "Y_VIS");
    private final static QName _T1_QNAME = new QName("", "T1");
    private final static QName _HOTX_QNAME = new QName("", "HOT_X");
    private final static QName _START_QNAME = new QName("", "START");
    private final static QName _HOTY_QNAME = new QName("", "HOT_Y");
    private final static QName _C2PCLINETYPE_QNAME = new QName("", "C2PC_LINE_TYPE");
    private final static QName _IMAGEREGISTERED_QNAME = new QName("", "IMAGE_REGISTERED");
    private final static QName _BLINK_QNAME = new QName("", "BLINK");
    private final static QName _METADATA_QNAME = new QName("", "METADATA");
    private final static QName _MVIS_QNAME = new QName("", "M_VIS");
    private final static QName _ENDTIME_QNAME = new QName("", "END_TIME");
    private final static QName _OLELOCALFILE_QNAME = new QName("", "OLE_LOCAL_FILE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ovl.schema.c2pc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MODEL }
     * 
     */
    public MODEL createMODEL() {
        return new MODEL();
    }

    /**
     * Create an instance of {@link CircleType }
     * 
     */
    public CircleType createCircleType() {
        return new CircleType();
    }

    /**
     * Create an instance of {@link C2PCimageType }
     * 
     */
    public C2PCimageType createC2PCimageType() {
        return new C2PCimageType();
    }

    /**
     * Create an instance of {@link C2PcoleobjectType }
     * 
     */
    public C2PcoleobjectType createC2PcoleobjectType() {
        return new C2PcoleobjectType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link ArrowType }
     * 
     */
    public ArrowType createArrowType() {
        return new ArrowType();
    }

    /**
     * Create an instance of {@link BoxType }
     * 
     */
    public BoxType createBoxType() {
        return new BoxType();
    }

    /**
     * Create an instance of {@link EllipseType }
     * 
     */
    public EllipseType createEllipseType() {
        return new EllipseType();
    }

    /**
     * Create an instance of {@link ArcType }
     * 
     */
    public ArcType createArcType() {
        return new ArcType();
    }

    /**
     * Create an instance of {@link PolygonType }
     * 
     */
    public PolygonType createPolygonType() {
        return new PolygonType();
    }

    /**
     * Create an instance of {@link RectangleType }
     * 
     */
    public RectangleType createRectangleType() {
        return new RectangleType();
    }

    /**
     * Create an instance of {@link SectorType }
     * 
     */
    public SectorType createSectorType() {
        return new SectorType();
    }

    /**
     * Create an instance of {@link SymbolType }
     * 
     */
    public SymbolType createSymbolType() {
        return new SymbolType();
    }

    /**
     * Create an instance of {@link UnitType }
     * 
     */
    public UnitType createUnitType() {
        return new UnitType();
    }

    /**
     * Create an instance of {@link CorridorType }
     * 
     */
    public CorridorType createCorridorType() {
        return new CorridorType();
    }

    /**
     * Create an instance of {@link BitmapType }
     * 
     */
    public BitmapType createBitmapType() {
        return new BitmapType();
    }

    /**
     * Create an instance of {@link TacsymbolType }
     * 
     */
    public TacsymbolType createTacsymbolType() {
        return new TacsymbolType();
    }

    /**
     * Create an instance of {@link MilbcorridorType }
     * 
     */
    public MilbcorridorType createMilbcorridorType() {
        return new MilbcorridorType();
    }

    /**
     * Create an instance of {@link MilbobjectType }
     * 
     */
    public MilbobjectType createMilbobjectType() {
        return new MilbobjectType();
    }

    /**
     * Create an instance of {@link BoundaryType }
     * 
     */
    public BoundaryType createBoundaryType() {
        return new BoundaryType();
    }

    /**
     * Create an instance of {@link GroupType }
     * 
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link ObjectGroup }
     * 
     */
    public ObjectGroup createObjectGroup() {
        return new ObjectGroup();
    }

    /**
     * Create an instance of {@link ACLType }
     * 
     */
    public ACLType createACLType() {
        return new ACLType();
    }

    /**
     * Create an instance of {@link ACPType }
     * 
     */
    public ACPType createACPType() {
        return new ACPType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT_OFFSET_Y")
    public JAXBElement<Long> createTEXTOFFSETY(Long value) {
        return new JAXBElement<Long>(_TEXTOFFSETY_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "K_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createKVIS(Boolean value) {
        return new JAXBElement<Boolean>(_KVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT_OFFSET_X")
    public JAXBElement<Long> createTEXTOFFSETX(Long value) {
        return new JAXBElement<Long>(_TEXTOFFSETX_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "H1_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createH1VIS(Boolean value) {
        return new JAXBElement<Boolean>(_H1VIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "W1")
    public JAXBElement<String> createW1(String value) {
        return new JAXBElement<String>(_W1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CREATE_TIME")
    public JAXBElement<Integer> createCREATETIME(Integer value) {
        return new JAXBElement<Integer>(_CREATETIME_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link BigDecimal }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "REFERENCE_POINT", defaultValue = "0.0 0.0")
    public JAXBElement<List<BigDecimal>> createREFERENCEPOINT(List<BigDecimal> value) {
        return new JAXBElement<List<BigDecimal>>(_REFERENCEPOINT_QNAME, ((Class) List.class), null, ((List<BigDecimal> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "S_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createSVIS(Boolean value) {
        return new JAXBElement<Boolean>(_SVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ROW")
    public JAXBElement<String> createROW(String value) {
        return new JAXBElement<String>(_ROW_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "H_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createHVIS(Boolean value) {
        return new JAXBElement<Boolean>(_HVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Q_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createQVIS(Boolean value) {
        return new JAXBElement<Boolean>(_QVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "START_DISPLAY_TIME")
    public JAXBElement<Long> createSTARTDISPLAYTIME(Long value) {
        return new JAXBElement<Long>(_STARTDISPLAYTIME_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SEMI_MAJOR")
    public JAXBElement<BigDecimal> createSEMIMAJOR(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_SEMIMAJOR_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ROLE_ICON_VIS", defaultValue = "true")
    public JAXBElement<Boolean> createROLEICONVIS(Boolean value) {
        return new JAXBElement<Boolean>(_ROLEICONVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "L_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createLVIS(Boolean value) {
        return new JAXBElement<Boolean>(_LVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CUSTOM_TOOLTIP")
    public JAXBElement<String> createCUSTOMTOOLTIP(String value) {
        return new JAXBElement<String>(_CUSTOMTOOLTIP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LINE_STYLE", defaultValue = "0")
    public JAXBElement<BigInteger> createLINESTYLE(BigInteger value) {
        return new JAXBElement<BigInteger>(_LINESTYLE_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link BigDecimal }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CENTER")
    public JAXBElement<List<BigDecimal>> createCENTER(List<BigDecimal> value) {
        return new JAXBElement<List<BigDecimal>>(_CENTER_QNAME, ((Class) List.class), null, ((List<BigDecimal> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AUTO_OFF_TOGGLE", defaultValue = "false")
    public JAXBElement<Boolean> createAUTOOFFTOGGLE(Boolean value) {
        return new JAXBElement<Boolean>(_AUTOOFFTOGGLE_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ENDBEARING")
    public JAXBElement<BigDecimal> createENDBEARING(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ENDBEARING_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NAME")
    public JAXBElement<String> createNAME(String value) {
        return new JAXBElement<String>(_NAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DESCRIPTION")
    public JAXBElement<String> createDESCRIPTION(String value) {
        return new JAXBElement<String>(_DESCRIPTION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OUTER_RADIUS")
    public JAXBElement<BigDecimal> createOUTERRADIUS(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_OUTERRADIUS_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "INSERT")
    public JAXBElement<String> createINSERT(String value) {
        return new JAXBElement<String>(_INSERT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SCALE_LINES_REFERENCE")
    public JAXBElement<Long> createSCALELINESREFERENCE(Long value) {
        return new JAXBElement<Long>(_SCALELINESREFERENCE_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "METADATA_TITLE")
    public JAXBElement<String> createMETADATATITLE(String value) {
        return new JAXBElement<String>(_METADATATITLE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "START_TIME")
    public JAXBElement<Integer> createSTARTTIME(Integer value) {
        return new JAXBElement<Integer>(_STARTTIME_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TACTICAL_DATA_TYPE")
    public JAXBElement<String> createTACTICALDATATYPE(String value) {
        return new JAXBElement<String>(_TACTICALDATATYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "W_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createWVIS(Boolean value) {
        return new JAXBElement<Boolean>(_WVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT_LABEL_SHOW")
    public JAXBElement<Long> createTEXTLABELSHOW(Long value) {
        return new JAXBElement<Long>(_TEXTLABELSHOW_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FRAME_FILL_VIS", defaultValue = "true")
    public JAXBElement<Boolean> createFRAMEFILLVIS(Boolean value) {
        return new JAXBElement<Boolean>(_FRAMEFILLVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SYMBOL_SIZE", defaultValue = "21")
    public JAXBElement<BigInteger> createSYMBOLSIZE(BigInteger value) {
        return new JAXBElement<BigInteger>(_SYMBOLSIZE_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "T_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createTVIS(Boolean value) {
        return new JAXBElement<Boolean>(_TVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "C_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createCVIS(Boolean value) {
        return new JAXBElement<Boolean>(_CVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FONT", defaultValue = "Arial:3:12")
    public JAXBElement<String> createFONT(String value) {
        return new JAXBElement<String>(_FONT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TIME_ALERT_MSG")
    public JAXBElement<String> createTIMEALERTMSG(String value) {
        return new JAXBElement<String>(_TIMEALERTMSG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link BigDecimal }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MAP_CENTER", defaultValue = "0.0 0.0")
    public JAXBElement<List<BigDecimal>> createMAPCENTER(List<BigDecimal> value) {
        return new JAXBElement<List<BigDecimal>>(_MAPCENTER_QNAME, ((Class) List.class), null, ((List<BigDecimal> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AC_DISPLAY_MASK")
    public JAXBElement<Long> createACDISPLAYMASK(Long value) {
        return new JAXBElement<Long>(_ACDISPLAYMASK_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MIL_ID")
    public JAXBElement<String> createMILID(String value) {
        return new JAXBElement<String>(_MILID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LINE_TYPE", defaultValue = "0")
    public JAXBElement<BigInteger> createLINETYPE(BigInteger value) {
        return new JAXBElement<BigInteger>(_LINETYPE_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OLEDATA")
    public JAXBElement<String> createOLEDATA(String value) {
        return new JAXBElement<String>(_OLEDATA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "READ_ONLY", defaultValue = "false")
    public JAXBElement<Boolean> createREADONLY(Boolean value) {
        return new JAXBElement<Boolean>(_READONLY_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "F")
    public JAXBElement<Integer> createF(Integer value) {
        return new JAXBElement<Integer>(_F_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "T1_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createT1VIS(Boolean value) {
        return new JAXBElement<Boolean>(_T1VIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "W1_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createW1VIS(Boolean value) {
        return new JAXBElement<Boolean>(_W1VIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OUTER_TEXT")
    public JAXBElement<String> createOUTERTEXT(String value) {
        return new JAXBElement<String>(_OUTERTEXT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G")
    public JAXBElement<String> createG(String value) {
        return new JAXBElement<String>(_G_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "URN")
    public JAXBElement<String> createURN(String value) {
        return new JAXBElement<String>(_URN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT_EDGE_COLOR")
    public JAXBElement<String> createTEXTEDGECOLOR(String value) {
        return new JAXBElement<String>(_TEXTEDGECOLOR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VISIBILITY", defaultValue = "true")
    public JAXBElement<Boolean> createVISIBILITY(Boolean value) {
        return new JAXBElement<Boolean>(_VISIBILITY_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "C")
    public JAXBElement<BigDecimal> createC(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_C_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HEIGHT")
    public JAXBElement<Integer> createHEIGHT(Integer value) {
        return new JAXBElement<Integer>(_HEIGHT_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "L")
    public JAXBElement<String> createL(String value) {
        return new JAXBElement<String>(_L_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "M")
    public JAXBElement<String> createM(String value) {
        return new JAXBElement<String>(_M_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TIME_ALERT_ENABLED")
    public JAXBElement<Boolean> createTIMEALERTENABLED(Boolean value) {
        return new JAXBElement<Boolean>(_TIMEALERTENABLED_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VMF_TYPE")
    public JAXBElement<String> createVMFTYPE(String value) {
        return new JAXBElement<String>(_VMFTYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "N")
    public JAXBElement<String> createN(String value) {
        return new JAXBElement<String>(_N_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "H")
    public JAXBElement<String> createH(String value) {
        return new JAXBElement<String>(_H_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "J")
    public JAXBElement<String> createJ(String value) {
        return new JAXBElement<String>(_J_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "N_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createNVIS(Boolean value) {
        return new JAXBElement<Boolean>(_NVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ITEXT")
    public JAXBElement<String> createITEXT(String value) {
        return new JAXBElement<String>(_ITEXT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "K")
    public JAXBElement<String> createK(String value) {
        return new JAXBElement<String>(_K_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STARTBEARING")
    public JAXBElement<BigDecimal> createSTARTBEARING(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_STARTBEARING_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "T")
    public JAXBElement<String> createT(String value) {
        return new JAXBElement<String>(_T_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "W")
    public JAXBElement<String> createW(String value) {
        return new JAXBElement<String>(_W_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT_STRIKETHROUGH")
    public JAXBElement<Long> createTEXTSTRIKETHROUGH(Long value) {
        return new JAXBElement<Long>(_TEXTSTRIKETHROUGH_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CROSSED", defaultValue = "false")
    public JAXBElement<Boolean> createCROSSED(Boolean value) {
        return new JAXBElement<Boolean>(_CROSSED_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OPT_FRAME_VIS", defaultValue = "true")
    public JAXBElement<Boolean> createOPTFRAMEVIS(Boolean value) {
        return new JAXBElement<Boolean>(_OPTFRAMEVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "V")
    public JAXBElement<String> createV(String value) {
        return new JAXBElement<String>(_V_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SPD_LDR_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createSPDLDRVIS(Boolean value) {
        return new JAXBElement<Boolean>(_SPDLDRVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Q")
    public JAXBElement<BigDecimal> createQ(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Q_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "P")
    public JAXBElement<String> createP(String value) {
        return new JAXBElement<String>(_P_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MIN_SCALE", defaultValue = "2147483647")
    public JAXBElement<Integer> createMINSCALE(Integer value) {
        return new JAXBElement<Integer>(_MINSCALE_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Y")
    public JAXBElement<String> createY(String value) {
        return new JAXBElement<String>(_Y_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "URL")
    public JAXBElement<String> createURL(String value) {
        return new JAXBElement<String>(_URL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "X")
    public JAXBElement<BigDecimal> createX(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_X_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Z")
    public JAXBElement<BigDecimal> createZ(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Z_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TIME_ALERT_DTG")
    public JAXBElement<Object> createTIMEALERTDTG(Object value) {
        return new JAXBElement<Object>(_TIMEALERTDTG_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FILL_TYPE", defaultValue = "1")
    public JAXBElement<Integer> createFILLTYPE(Integer value) {
        return new JAXBElement<Integer>(_FILLTYPE_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "INNER_RADIUS")
    public JAXBElement<BigDecimal> createINNERRADIUS(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_INNERRADIUS_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "J_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createJVIS(Boolean value) {
        return new JAXBElement<Boolean>(_JVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PRIORITY", defaultValue = "50")
    public JAXBElement<Integer> createPRIORITY(Integer value) {
        return new JAXBElement<Integer>(_PRIORITY_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BOUNDARY_ALERT_ENTER_ENABLED")
    public JAXBElement<Boolean> createBOUNDARYALERTENTERENABLED(Boolean value) {
        return new JAXBElement<Boolean>(_BOUNDARYALERTENTERENABLED_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "INNER_TEXT")
    public JAXBElement<String> createINNERTEXT(String value) {
        return new JAXBElement<String>(_INNERTEXT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BEARING", defaultValue = "0.0")
    public JAXBElement<BigDecimal> createBEARING(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_BEARING_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WIDTH")
    public JAXBElement<BigDecimal> createWIDTH(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_WIDTH_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "D_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createDVIS(Boolean value) {
        return new JAXBElement<Boolean>(_DVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SCALE_LINES")
    public JAXBElement<Long> createSCALELINES(Long value) {
        return new JAXBElement<Long>(_SCALELINES_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT_BACKGROUND_SHOW")
    public JAXBElement<Long> createTEXTBACKGROUNDSHOW(Long value) {
        return new JAXBElement<Long>(_TEXTBACKGROUNDSHOW_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXTCOLOR", defaultValue = "255 255 0")
    public JAXBElement<String> createTEXTCOLOR(String value) {
        return new JAXBElement<String>(_TEXTCOLOR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "F_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createFVIS(Boolean value) {
        return new JAXBElement<Boolean>(_FVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CLOSED", defaultValue = "false")
    public JAXBElement<Boolean> createCLOSED(Boolean value) {
        return new JAXBElement<Boolean>(_CLOSED_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "H1")
    public JAXBElement<String> createH1(String value) {
        return new JAXBElement<String>(_H1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AB_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createABVIS(Boolean value) {
        return new JAXBElement<Boolean>(_ABVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "END")
    public JAXBElement<Integer> createEND(Integer value) {
        return new JAXBElement<Integer>(_END_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SIZE", defaultValue = "18")
    public JAXBElement<BigDecimal> createSIZE(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_SIZE_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RADIUS")
    public JAXBElement<BigDecimal> createRADIUS(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_RADIUS_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "P_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createPVIS(Boolean value) {
        return new JAXBElement<Boolean>(_PVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OUTER_TEXT_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createOUTERTEXTVIS(Boolean value) {
        return new JAXBElement<Boolean>(_OUTERTEXTVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CUSTOM_INDEX")
    public JAXBElement<Long> createCUSTOMINDEX(Long value) {
        return new JAXBElement<Long>(_CUSTOMINDEX_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createEVIS(Boolean value) {
        return new JAXBElement<Boolean>(_EVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OTEXT")
    public JAXBElement<String> createOTEXT(String value) {
        return new JAXBElement<String>(_OTEXT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "G_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createGVIS(Boolean value) {
        return new JAXBElement<Boolean>(_GVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OLE_IMAGE_TYPE")
    public JAXBElement<String> createOLEIMAGETYPE(String value) {
        return new JAXBElement<String>(_OLEIMAGETYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "INNER_TEXT_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createINNERTEXTVIS(Boolean value) {
        return new JAXBElement<Boolean>(_INNERTEXTVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT_UNDERLINE")
    public JAXBElement<Long> createTEXTUNDERLINE(Long value) {
        return new JAXBElement<Long>(_TEXTUNDERLINE_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT_WIDTH")
    public JAXBElement<Long> createTEXTWIDTH(Long value) {
        return new JAXBElement<Long>(_TEXTWIDTH_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OLE_DATA_SIZE")
    public JAXBElement<Long> createOLEDATASIZE(Long value) {
        return new JAXBElement<Long>(_OLEDATASIZE_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SOURCE")
    public JAXBElement<String> createSOURCE(String value) {
        return new JAXBElement<String>(_SOURCE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CAT_THREAT")
    public JAXBElement<String> createCATTHREAT(String value) {
        return new JAXBElement<String>(_CATTHREAT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "INSERT_SIZE")
    public JAXBElement<BigDecimal> createINSERTSIZE(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_INSERTSIZE_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RIGHT_BEARING")
    public JAXBElement<BigDecimal> createRIGHTBEARING(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_RIGHTBEARING_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "END_DISPLAY_TIME")
    public JAXBElement<Long> createENDDISPLAYTIME(Long value) {
        return new JAXBElement<Long>(_ENDDISPLAYTIME_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT_EDGE_SHOW")
    public JAXBElement<Long> createTEXTEDGESHOW(Long value) {
        return new JAXBElement<Long>(_TEXTEDGESHOW_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OLE_CLSID")
    public JAXBElement<String> createOLECLSID(String value) {
        return new JAXBElement<String>(_OLECLSID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link BigDecimal }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "POSITION")
    public JAXBElement<List<BigDecimal>> createPOSITION(List<BigDecimal> value) {
        return new JAXBElement<List<BigDecimal>>(_POSITION_QNAME, ((Class) List.class), null, ((List<BigDecimal> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MAX_SCALE", defaultValue = "1")
    public JAXBElement<Integer> createMAXSCALE(Integer value) {
        return new JAXBElement<Integer>(_MAXSCALE_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LENGTH")
    public JAXBElement<BigDecimal> createLENGTH(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_LENGTH_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ORG")
    public JAXBElement<String> createORG(String value) {
        return new JAXBElement<String>(_ORG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LABEL_TYPE", defaultValue = "None")
    public JAXBElement<String> createLABELTYPE(String value) {
        return new JAXBElement<String>(_LABELTYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link BigDecimal }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "POINT2")
    public JAXBElement<List<BigDecimal>> createPOINT2(List<BigDecimal> value) {
        return new JAXBElement<List<BigDecimal>>(_POINT2_QNAME, ((Class) List.class), null, ((List<BigDecimal> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OLE_IMAGE_DATA")
    public JAXBElement<String> createOLEIMAGEDATA(String value) {
        return new JAXBElement<String>(_OLEIMAGEDATA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link BigDecimal }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "POINT1")
    public JAXBElement<List<BigDecimal>> createPOINT1(List<BigDecimal> value) {
        return new JAXBElement<List<BigDecimal>>(_POINT1_QNAME, ((Class) List.class), null, ((List<BigDecimal> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AA_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createAAVIS(Boolean value) {
        return new JAXBElement<Boolean>(_AAVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ROUNDED_CORNERS")
    public JAXBElement<Boolean> createROUNDEDCORNERS(Boolean value) {
        return new JAXBElement<Boolean>(_ROUNDEDCORNERS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AA")
    public JAXBElement<String> createAA(String value) {
        return new JAXBElement<String>(_AA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT_LABEL_SCALE")
    public JAXBElement<Long> createTEXTLABELSCALE(Long value) {
        return new JAXBElement<Long>(_TEXTLABELSCALE_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IMAGE_FILE")
    public JAXBElement<String> createIMAGEFILE(String value) {
        return new JAXBElement<String>(_IMAGEFILE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MAP_WIDTH")
    public JAXBElement<BigDecimal> createMAPWIDTH(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_MAPWIDTH_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SEMI_MINOR")
    public JAXBElement<BigDecimal> createSEMIMINOR(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_SEMIMINOR_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AFFILIATION")
    public JAXBElement<String> createAFFILIATION(String value) {
        return new JAXBElement<String>(_AFFILIATION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LINE_COLOR", defaultValue = "255 255 0")
    public JAXBElement<String> createLINECOLOR(String value) {
        return new JAXBElement<String>(_LINECOLOR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "REMARKS")
    public JAXBElement<String> createREMARKS(String value) {
        return new JAXBElement<String>(_REMARKS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "X_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createXVIS(Boolean value) {
        return new JAXBElement<Boolean>(_XVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT_HEIGHT")
    public JAXBElement<Long> createTEXTHEIGHT(Long value) {
        return new JAXBElement<Long>(_TEXTHEIGHT_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ROTATION")
    public JAXBElement<BigDecimal> createROTATION(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ROTATION_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT_ALIGNMENT")
    public JAXBElement<Long> createTEXTALIGNMENT(Long value) {
        return new JAXBElement<Long>(_TEXTALIGNMENT_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LINE_GEOM", defaultValue = "1")
    public JAXBElement<BigInteger> createLINEGEOM(BigInteger value) {
        return new JAXBElement<BigInteger>(_LINEGEOM_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FILL_COLOR", defaultValue = "0 0 0")
    public JAXBElement<String> createFILLCOLOR(String value) {
        return new JAXBElement<String>(_FILLCOLOR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IMAGE_TRANSPARENCY")
    public JAXBElement<Integer> createIMAGETRANSPARENCY(Integer value) {
        return new JAXBElement<Integer>(_IMAGETRANSPARENCY_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VISIBLE", defaultValue = "true")
    public JAXBElement<String> createVISIBLE(String value) {
        return new JAXBElement<String>(_VISIBLE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MODIFIED_TIME")
    public JAXBElement<Integer> createMODIFIEDTIME(Integer value) {
        return new JAXBElement<Integer>(_MODIFIEDTIME_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "REPRESENTATION")
    public JAXBElement<String> createREPRESENTATION(String value) {
        return new JAXBElement<String>(_REPRESENTATION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT_BACKGROUND_COLOR")
    public JAXBElement<String> createTEXTBACKGROUNDCOLOR(String value) {
        return new JAXBElement<String>(_TEXTBACKGROUNDCOLOR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "THREAT")
    public JAXBElement<String> createTHREAT(String value) {
        return new JAXBElement<String>(_THREAT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ECHELON")
    public JAXBElement<String> createECHELON(String value) {
        return new JAXBElement<String>(_ECHELON_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT")
    public JAXBElement<String> createTEXT(String value) {
        return new JAXBElement<String>(_TEXT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Z_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createZVIS(Boolean value) {
        return new JAXBElement<Boolean>(_ZVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SCALE_ACTIVATED", defaultValue = "false")
    public JAXBElement<Boolean> createSCALEACTIVATED(Boolean value) {
        return new JAXBElement<Boolean>(_SCALEACTIVATED_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LINE_WIDTH", defaultValue = "1")
    public JAXBElement<BigInteger> createLINEWIDTH(BigInteger value) {
        return new JAXBElement<BigInteger>(_LINEWIDTH_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LEFT_BEARING")
    public JAXBElement<BigDecimal> createLEFTBEARING(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_LEFTBEARING_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "V_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createVVIS(Boolean value) {
        return new JAXBElement<Boolean>(_VVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LABEL")
    public JAXBElement<String> createLABEL(String value) {
        return new JAXBElement<String>(_LABEL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ENABLE_ONOFF_BY_DTG")
    public JAXBElement<Long> createENABLEONOFFBYDTG(Long value) {
        return new JAXBElement<Long>(_ENABLEONOFFBYDTG_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Y_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createYVIS(Boolean value) {
        return new JAXBElement<Boolean>(_YVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "T1")
    public JAXBElement<String> createT1(String value) {
        return new JAXBElement<String>(_T1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HOT_X")
    public JAXBElement<Integer> createHOTX(Integer value) {
        return new JAXBElement<Integer>(_HOTX_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "START")
    public JAXBElement<Integer> createSTART(Integer value) {
        return new JAXBElement<Integer>(_START_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HOT_Y")
    public JAXBElement<Integer> createHOTY(Integer value) {
        return new JAXBElement<Integer>(_HOTY_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "C2PC_LINE_TYPE")
    public JAXBElement<Long> createC2PCLINETYPE(Long value) {
        return new JAXBElement<Long>(_C2PCLINETYPE_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IMAGE_REGISTERED", defaultValue = "false")
    public JAXBElement<Boolean> createIMAGEREGISTERED(Boolean value) {
        return new JAXBElement<Boolean>(_IMAGEREGISTERED_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BLINK", defaultValue = "false")
    public JAXBElement<Boolean> createBLINK(Boolean value) {
        return new JAXBElement<Boolean>(_BLINK_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "METADATA")
    public JAXBElement<String> createMETADATA(String value) {
        return new JAXBElement<String>(_METADATA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "M_VIS", defaultValue = "false")
    public JAXBElement<Boolean> createMVIS(Boolean value) {
        return new JAXBElement<Boolean>(_MVIS_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "END_TIME")
    public JAXBElement<Integer> createENDTIME(Integer value) {
        return new JAXBElement<Integer>(_ENDTIME_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OLE_LOCAL_FILE")
    public JAXBElement<String> createOLELOCALFILE(String value) {
        return new JAXBElement<String>(_OLELOCALFILE_QNAME, String.class, null, value);
    }

}
