//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.23 at 09:10:17 AM UTC 
//


package ovl.schema.c2pc;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tacsymbolType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tacsymbolType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MIL_ID" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element ref="{}NAME" minOccurs="0"/>
 *         &lt;element ref="{}DESCRIPTION" minOccurs="0"/>
 *         &lt;element ref="{}REMARKS" minOccurs="0"/>
 *         &lt;element ref="{}MAX_SCALE" minOccurs="0"/>
 *         &lt;element ref="{}MIN_SCALE" minOccurs="0"/>
 *         &lt;element ref="{}SCALE_ACTIVATED" minOccurs="0"/>
 *         &lt;element ref="{}LABEL_TYPE" minOccurs="0"/>
 *         &lt;element ref="{}VISIBILITY" minOccurs="0"/>
 *         &lt;element ref="{}PRIORITY" minOccurs="0"/>
 *         &lt;element name="LINE_COLOR" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="FILL_COLOR" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="FILL_TYPE" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="LINE_TYPE" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="LINE_STYLE" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="LINE_WIDTH" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="LINE_GEOM" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element ref="{}BLINK" minOccurs="0"/>
 *         &lt;element ref="{}C2PC_LINE_TYPE" minOccurs="0"/>
 *         &lt;element ref="{}SCALE_LINES" minOccurs="0"/>
 *         &lt;element ref="{}SCALE_LINES_REFERENCE" minOccurs="0"/>
 *         &lt;element ref="{}TEXT" minOccurs="0"/>
 *         &lt;element ref="{}TEXTCOLOR" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_EDGE_COLOR" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_BACKGROUND_COLOR" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_EDGE_SHOW" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_LABEL_SHOW" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_LABEL_SCALE" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_UNDERLINE" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_STRIKETHROUGH" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_HEIGHT" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_WIDTH" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_OFFSET_X" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_OFFSET_Y" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_ALIGNMENT" minOccurs="0"/>
 *         &lt;element ref="{}TEXT_BACKGROUND_SHOW" minOccurs="0"/>
 *         &lt;element ref="{}FONT" minOccurs="0"/>
 *         &lt;element ref="{}METADATA" minOccurs="0"/>
 *         &lt;element ref="{}METADATA_TITLE" minOccurs="0"/>
 *         &lt;element ref="{}CUSTOM_INDEX" minOccurs="0"/>
 *         &lt;element ref="{}CUSTOM_TOOLTIP" minOccurs="0"/>
 *         &lt;element ref="{}ROTATION" minOccurs="0"/>
 *         &lt;element ref="{}AFFILIATION" minOccurs="0"/>
 *         &lt;element ref="{}URN" minOccurs="0"/>
 *         &lt;element ref="{}TACTICAL_DATA_TYPE" minOccurs="0"/>
 *         &lt;element ref="{}TIME_ALERT_ENABLED" minOccurs="0"/>
 *         &lt;element ref="{}TIME_ALERT_MSG" minOccurs="0"/>
 *         &lt;element ref="{}TIME_ALERT_DTG" minOccurs="0"/>
 *         &lt;element ref="{}BOUNDARY_ALERT_ENTER_ENABLED" minOccurs="0"/>
 *         &lt;element ref="{}START_DISPLAY_TIME" minOccurs="0"/>
 *         &lt;element ref="{}END_DISPLAY_TIME" minOccurs="0"/>
 *         &lt;element ref="{}ENABLE_ONOFF_BY_DTG" minOccurs="0"/>
 *         &lt;element ref="{}MODIFIED_TIME" minOccurs="0"/>
 *         &lt;element ref="{}CREATE_TIME" minOccurs="0"/>
 *         &lt;element ref="{}W1" minOccurs="0"/>
 *         &lt;element ref="{}SOURCE" minOccurs="0"/>
 *         &lt;element ref="{}SIZE" minOccurs="0"/>
 *         &lt;element ref="{}URL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CLOSED" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="MIL_PLOT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="MOOTW_PLOT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="SYMBOL_FILL" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="NTDS_PLOT_ID" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element ref="{}AA" minOccurs="0"/>
 *         &lt;element ref="{}AA_VIS" minOccurs="0"/>
 *         &lt;element ref="{}AB_VIS" minOccurs="0"/>
 *         &lt;element name="C" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="C_VIS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean">
 *               &lt;pattern value="false"/>
 *               &lt;pattern value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{}D_VIS" minOccurs="0"/>
 *         &lt;element ref="{}F" minOccurs="0"/>
 *         &lt;element ref="{}F_VIS" minOccurs="0"/>
 *         &lt;element ref="{}G" minOccurs="0"/>
 *         &lt;element ref="{}G_VIS" minOccurs="0"/>
 *         &lt;element ref="{}H" minOccurs="0"/>
 *         &lt;element ref="{}H_VIS" minOccurs="0"/>
 *         &lt;element ref="{}H1" minOccurs="0"/>
 *         &lt;element ref="{}H1_VIS" minOccurs="0"/>
 *         &lt;element name="H2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="H2_VIS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean">
 *               &lt;pattern value="false"/>
 *               &lt;pattern value="true"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{}J" minOccurs="0"/>
 *         &lt;element ref="{}J_VIS" minOccurs="0"/>
 *         &lt;element ref="{}K" minOccurs="0"/>
 *         &lt;element ref="{}K_VIS" minOccurs="0"/>
 *         &lt;element ref="{}L" minOccurs="0"/>
 *         &lt;element ref="{}L_VIS" minOccurs="0"/>
 *         &lt;element ref="{}M" minOccurs="0"/>
 *         &lt;element ref="{}M_VIS" minOccurs="0"/>
 *         &lt;element ref="{}N" minOccurs="0"/>
 *         &lt;element ref="{}N_VIS" minOccurs="0"/>
 *         &lt;element ref="{}P" minOccurs="0"/>
 *         &lt;element ref="{}P_VIS" minOccurs="0"/>
 *         &lt;element ref="{}S_VIS" minOccurs="0"/>
 *         &lt;element ref="{}T" minOccurs="0"/>
 *         &lt;element ref="{}T_VIS" minOccurs="0"/>
 *         &lt;element ref="{}V" minOccurs="0"/>
 *         &lt;element ref="{}V_VIS" minOccurs="0"/>
 *         &lt;element ref="{}W" minOccurs="0"/>
 *         &lt;element ref="{}W_VIS" minOccurs="0"/>
 *         &lt;element ref="{}X" minOccurs="0"/>
 *         &lt;element ref="{}X_VIS" minOccurs="0"/>
 *         &lt;element ref="{}Y" minOccurs="0"/>
 *         &lt;element ref="{}Y_VIS" minOccurs="0"/>
 *         &lt;element ref="{}Z" minOccurs="0"/>
 *         &lt;element ref="{}Z_VIS" minOccurs="0"/>
 *         &lt;element ref="{}Q" minOccurs="0"/>
 *         &lt;element name="Q_VIS" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element ref="{}E_VIS" minOccurs="0"/>
 *         &lt;element ref="{}POSITION"/>
 *         &lt;element ref="{}FRAME_FILL_VIS" minOccurs="0"/>
 *         &lt;element ref="{}OPT_FRAME_VIS" minOccurs="0"/>
 *         &lt;element ref="{}ROLE_ICON_VIS" minOccurs="0"/>
 *         &lt;element ref="{}SPD_LDR_VIS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tacsymbolType", propOrder = {
    "milid",
    "name",
    "description",
    "remarks",
    "maxscale",
    "minscale",
    "scaleactivated",
    "labeltype",
    "visibility",
    "priority",
    "linecolor",
    "fillcolor",
    "filltype",
    "linetype",
    "linestyle",
    "linewidth",
    "linegeom",
    "blink",
    "c2PCLINETYPE",
    "scalelines",
    "scalelinesreference",
    "text",
    "textcolor",
    "textedgecolor",
    "textbackgroundcolor",
    "textedgeshow",
    "textlabelshow",
    "textlabelscale",
    "textunderline",
    "textstrikethrough",
    "textheight",
    "textwidth",
    "textoffsetx",
    "textoffsety",
    "textalignment",
    "textbackgroundshow",
    "font",
    "metadata",
    "metadatatitle",
    "customindex",
    "customtooltip",
    "rotation",
    "affiliation",
    "urn",
    "tacticaldatatype",
    "timealertenabled",
    "timealertmsg",
    "timealertdtg",
    "boundaryalertenterenabled",
    "startdisplaytime",
    "enddisplaytime",
    "enableonoffbydtg",
    "modifiedtime",
    "createtime",
    "w1",
    "source",
    "size",
    "url",
    "closed",
    "milplot",
    "mootwplot",
    "symbolfill",
    "ntdsplotid",
    "aa",
    "aavis",
    "abvis",
    "c",
    "cvis",
    "dvis",
    "f",
    "fvis",
    "g",
    "gvis",
    "h",
    "hvis",
    "h1",
    "h1VIS",
    "h2",
    "h2VIS",
    "j",
    "jvis",
    "k",
    "kvis",
    "l",
    "lvis",
    "m",
    "mvis",
    "n",
    "nvis",
    "p",
    "pvis",
    "svis",
    "t",
    "tvis",
    "v",
    "vvis",
    "w",
    "wvis",
    "x",
    "xvis",
    "y",
    "yvis",
    "z",
    "zvis",
    "q",
    "qvis",
    "evis",
    "position",
    "framefillvis",
    "optframevis",
    "roleiconvis",
    "spdldrvis"
})
public class TacsymbolType {

    @XmlElement(name = "MIL_ID", required = true)
    protected Object milid;
    @XmlElement(name = "NAME")
    protected String name;
    @XmlElement(name = "DESCRIPTION")
    protected String description;
    @XmlElement(name = "REMARKS")
    protected String remarks;
    @XmlElement(name = "MAX_SCALE", defaultValue = "1")
    protected Integer maxscale;
    @XmlElement(name = "MIN_SCALE", defaultValue = "2147483647")
    protected Integer minscale;
    @XmlElement(name = "SCALE_ACTIVATED", defaultValue = "false")
    protected Boolean scaleactivated;
    @XmlElement(name = "LABEL_TYPE", defaultValue = "None")
    protected String labeltype;
    @XmlElement(name = "VISIBILITY", defaultValue = "true")
    protected Boolean visibility;
    @XmlElement(name = "PRIORITY", defaultValue = "50")
    protected Integer priority;
    @XmlElement(name = "LINE_COLOR")
    protected Object linecolor;
    @XmlElement(name = "FILL_COLOR")
    protected Object fillcolor;
    @XmlElement(name = "FILL_TYPE")
    protected Object filltype;
    @XmlElement(name = "LINE_TYPE")
    protected Object linetype;
    @XmlElement(name = "LINE_STYLE")
    protected Object linestyle;
    @XmlElement(name = "LINE_WIDTH")
    protected Object linewidth;
    @XmlElement(name = "LINE_GEOM")
    protected Object linegeom;
    @XmlElement(name = "BLINK", defaultValue = "false")
    protected Boolean blink;
    @XmlElement(name = "C2PC_LINE_TYPE")
    protected Long c2PCLINETYPE;
    @XmlElement(name = "SCALE_LINES")
    protected Long scalelines;
    @XmlElement(name = "SCALE_LINES_REFERENCE")
    protected Long scalelinesreference;
    @XmlElement(name = "TEXT")
    protected String text;
    @XmlElement(name = "TEXTCOLOR", defaultValue = "255 255 0")
    protected String textcolor;
    @XmlElement(name = "TEXT_EDGE_COLOR")
    protected String textedgecolor;
    @XmlElement(name = "TEXT_BACKGROUND_COLOR")
    protected String textbackgroundcolor;
    @XmlElement(name = "TEXT_EDGE_SHOW")
    protected Long textedgeshow;
    @XmlElement(name = "TEXT_LABEL_SHOW")
    protected Long textlabelshow;
    @XmlElement(name = "TEXT_LABEL_SCALE")
    protected Long textlabelscale;
    @XmlElement(name = "TEXT_UNDERLINE")
    protected Long textunderline;
    @XmlElement(name = "TEXT_STRIKETHROUGH")
    protected Long textstrikethrough;
    @XmlElement(name = "TEXT_HEIGHT")
    protected Long textheight;
    @XmlElement(name = "TEXT_WIDTH")
    protected Long textwidth;
    @XmlElement(name = "TEXT_OFFSET_X")
    protected Long textoffsetx;
    @XmlElement(name = "TEXT_OFFSET_Y")
    protected Long textoffsety;
    @XmlElement(name = "TEXT_ALIGNMENT")
    protected Long textalignment;
    @XmlElement(name = "TEXT_BACKGROUND_SHOW")
    protected Long textbackgroundshow;
    @XmlElement(name = "FONT", defaultValue = "Arial:3:12")
    protected String font;
    @XmlElement(name = "METADATA")
    protected String metadata;
    @XmlElement(name = "METADATA_TITLE")
    protected String metadatatitle;
    @XmlElement(name = "CUSTOM_INDEX")
    protected Long customindex;
    @XmlElement(name = "CUSTOM_TOOLTIP")
    protected String customtooltip;
    @XmlElement(name = "ROTATION")
    protected BigDecimal rotation;
    @XmlElement(name = "AFFILIATION")
    protected String affiliation;
    @XmlElement(name = "URN")
    protected String urn;
    @XmlElement(name = "TACTICAL_DATA_TYPE")
    protected String tacticaldatatype;
    @XmlElement(name = "TIME_ALERT_ENABLED")
    protected Boolean timealertenabled;
    @XmlElement(name = "TIME_ALERT_MSG")
    protected String timealertmsg;
    @XmlElement(name = "TIME_ALERT_DTG")
    protected Object timealertdtg;
    @XmlElement(name = "BOUNDARY_ALERT_ENTER_ENABLED")
    protected Boolean boundaryalertenterenabled;
    @XmlElement(name = "START_DISPLAY_TIME")
    protected Long startdisplaytime;
    @XmlElement(name = "END_DISPLAY_TIME")
    protected Long enddisplaytime;
    @XmlElement(name = "ENABLE_ONOFF_BY_DTG")
    protected Long enableonoffbydtg;
    @XmlElement(name = "MODIFIED_TIME")
    protected Integer modifiedtime;
    @XmlElement(name = "CREATE_TIME")
    protected Integer createtime;
    @XmlElement(name = "W1", nillable = true)
    protected String w1;
    @XmlElement(name = "SOURCE")
    protected String source;
    @XmlElement(name = "SIZE", defaultValue = "18")
    protected BigDecimal size;
    @XmlElement(name = "URL")
    protected List<String> url;
    @XmlElement(name = "CLOSED")
    protected Object closed;
    @XmlElement(name = "MIL_PLOT")
    protected Integer milplot;
    @XmlElement(name = "MOOTW_PLOT")
    protected Integer mootwplot;
    @XmlElement(name = "SYMBOL_FILL")
    protected Integer symbolfill;
    @XmlElement(name = "NTDS_PLOT_ID")
    protected Integer ntdsplotid;
    @XmlElement(name = "AA", nillable = true)
    protected String aa;
    @XmlElement(name = "AA_VIS", defaultValue = "false")
    protected Boolean aavis;
    @XmlElement(name = "AB_VIS", defaultValue = "false")
    protected Boolean abvis;
    @XmlElement(name = "C")
    protected BigInteger c;
    @XmlElement(name = "C_VIS")
    protected Boolean cvis;
    @XmlElement(name = "D_VIS", defaultValue = "false")
    protected Boolean dvis;
    @XmlElement(name = "F")
    protected Integer f;
    @XmlElement(name = "F_VIS", defaultValue = "false")
    protected Boolean fvis;
    @XmlElement(name = "G", nillable = true)
    protected String g;
    @XmlElement(name = "G_VIS", defaultValue = "false")
    protected Boolean gvis;
    @XmlElement(name = "H", nillable = true)
    protected String h;
    @XmlElement(name = "H_VIS", defaultValue = "false")
    protected Boolean hvis;
    @XmlElement(name = "H1", nillable = true)
    protected String h1;
    @XmlElement(name = "H1_VIS", defaultValue = "false")
    protected Boolean h1VIS;
    @XmlElement(name = "H2")
    protected String h2;
    @XmlElement(name = "H2_VIS")
    protected Boolean h2VIS;
    @XmlElement(name = "J", nillable = true)
    protected String j;
    @XmlElement(name = "J_VIS", defaultValue = "false")
    protected Boolean jvis;
    @XmlElement(name = "K", nillable = true)
    protected String k;
    @XmlElement(name = "K_VIS", defaultValue = "false")
    protected Boolean kvis;
    @XmlElement(name = "L", nillable = true)
    protected String l;
    @XmlElement(name = "L_VIS", defaultValue = "false")
    protected Boolean lvis;
    @XmlElement(name = "M", nillable = true)
    protected String m;
    @XmlElement(name = "M_VIS", defaultValue = "false")
    protected Boolean mvis;
    @XmlElement(name = "N", nillable = true)
    protected String n;
    @XmlElement(name = "N_VIS", defaultValue = "false")
    protected Boolean nvis;
    @XmlElement(name = "P", nillable = true)
    protected String p;
    @XmlElement(name = "P_VIS", defaultValue = "false")
    protected Boolean pvis;
    @XmlElement(name = "S_VIS", defaultValue = "false")
    protected Boolean svis;
    @XmlElement(name = "T", nillable = true)
    protected String t;
    @XmlElement(name = "T_VIS", defaultValue = "false")
    protected Boolean tvis;
    @XmlElement(name = "V", nillable = true)
    protected String v;
    @XmlElement(name = "V_VIS", defaultValue = "false")
    protected Boolean vvis;
    @XmlElement(name = "W", nillable = true)
    protected String w;
    @XmlElement(name = "W_VIS", defaultValue = "false")
    protected Boolean wvis;
    @XmlElement(name = "X", nillable = true)
    protected BigDecimal x;
    @XmlElement(name = "X_VIS", defaultValue = "false")
    protected Boolean xvis;
    @XmlElement(name = "Y", nillable = true)
    protected String y;
    @XmlElement(name = "Y_VIS", defaultValue = "false")
    protected Boolean yvis;
    @XmlElement(name = "Z", nillable = true)
    protected BigDecimal z;
    @XmlElement(name = "Z_VIS", defaultValue = "false")
    protected Boolean zvis;
    @XmlElement(name = "Q")
    protected BigDecimal q;
    @XmlElement(name = "Q_VIS")
    protected Object qvis;
    @XmlElement(name = "E_VIS", defaultValue = "false")
    protected Boolean evis;
    @XmlList
    @XmlElement(name = "POSITION", required = true)
    protected List<BigDecimal> position;
    @XmlElement(name = "FRAME_FILL_VIS", defaultValue = "true")
    protected Boolean framefillvis;
    @XmlElement(name = "OPT_FRAME_VIS", defaultValue = "true")
    protected Boolean optframevis;
    @XmlElement(name = "ROLE_ICON_VIS", defaultValue = "true")
    protected Boolean roleiconvis;
    @XmlElement(name = "SPD_LDR_VIS", defaultValue = "false")
    protected Boolean spdldrvis;

    /**
     * Gets the value of the milid property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMILID() {
        return milid;
    }

    /**
     * Sets the value of the milid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMILID(Object value) {
        this.milid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREMARKS() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREMARKS(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the maxscale property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMAXSCALE() {
        return maxscale;
    }

    /**
     * Sets the value of the maxscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMAXSCALE(Integer value) {
        this.maxscale = value;
    }

    /**
     * Gets the value of the minscale property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMINSCALE() {
        return minscale;
    }

    /**
     * Sets the value of the minscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMINSCALE(Integer value) {
        this.minscale = value;
    }

    /**
     * Gets the value of the scaleactivated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSCALEACTIVATED() {
        return scaleactivated;
    }

    /**
     * Sets the value of the scaleactivated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSCALEACTIVATED(Boolean value) {
        this.scaleactivated = value;
    }

    /**
     * Gets the value of the labeltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLABELTYPE() {
        return labeltype;
    }

    /**
     * Sets the value of the labeltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLABELTYPE(String value) {
        this.labeltype = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVISIBILITY() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVISIBILITY(Boolean value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPRIORITY() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPRIORITY(Integer value) {
        this.priority = value;
    }

    /**
     * Gets the value of the linecolor property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLINECOLOR() {
        return linecolor;
    }

    /**
     * Sets the value of the linecolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLINECOLOR(Object value) {
        this.linecolor = value;
    }

    /**
     * Gets the value of the fillcolor property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFILLCOLOR() {
        return fillcolor;
    }

    /**
     * Sets the value of the fillcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFILLCOLOR(Object value) {
        this.fillcolor = value;
    }

    /**
     * Gets the value of the filltype property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getFILLTYPE() {
        return filltype;
    }

    /**
     * Sets the value of the filltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFILLTYPE(Object value) {
        this.filltype = value;
    }

    /**
     * Gets the value of the linetype property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLINETYPE() {
        return linetype;
    }

    /**
     * Sets the value of the linetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLINETYPE(Object value) {
        this.linetype = value;
    }

    /**
     * Gets the value of the linestyle property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLINESTYLE() {
        return linestyle;
    }

    /**
     * Sets the value of the linestyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLINESTYLE(Object value) {
        this.linestyle = value;
    }

    /**
     * Gets the value of the linewidth property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLINEWIDTH() {
        return linewidth;
    }

    /**
     * Sets the value of the linewidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLINEWIDTH(Object value) {
        this.linewidth = value;
    }

    /**
     * Gets the value of the linegeom property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLINEGEOM() {
        return linegeom;
    }

    /**
     * Sets the value of the linegeom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLINEGEOM(Object value) {
        this.linegeom = value;
    }

    /**
     * Gets the value of the blink property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBLINK() {
        return blink;
    }

    /**
     * Sets the value of the blink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBLINK(Boolean value) {
        this.blink = value;
    }

    /**
     * Gets the value of the c2PCLINETYPE property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getC2PCLINETYPE() {
        return c2PCLINETYPE;
    }

    /**
     * Sets the value of the c2PCLINETYPE property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setC2PCLINETYPE(Long value) {
        this.c2PCLINETYPE = value;
    }

    /**
     * Gets the value of the scalelines property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSCALELINES() {
        return scalelines;
    }

    /**
     * Sets the value of the scalelines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSCALELINES(Long value) {
        this.scalelines = value;
    }

    /**
     * Gets the value of the scalelinesreference property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSCALELINESREFERENCE() {
        return scalelinesreference;
    }

    /**
     * Sets the value of the scalelinesreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSCALELINESREFERENCE(Long value) {
        this.scalelinesreference = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXT() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXT(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the textcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXTCOLOR() {
        return textcolor;
    }

    /**
     * Sets the value of the textcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXTCOLOR(String value) {
        this.textcolor = value;
    }

    /**
     * Gets the value of the textedgecolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXTEDGECOLOR() {
        return textedgecolor;
    }

    /**
     * Sets the value of the textedgecolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXTEDGECOLOR(String value) {
        this.textedgecolor = value;
    }

    /**
     * Gets the value of the textbackgroundcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEXTBACKGROUNDCOLOR() {
        return textbackgroundcolor;
    }

    /**
     * Sets the value of the textbackgroundcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEXTBACKGROUNDCOLOR(String value) {
        this.textbackgroundcolor = value;
    }

    /**
     * Gets the value of the textedgeshow property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTEDGESHOW() {
        return textedgeshow;
    }

    /**
     * Sets the value of the textedgeshow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTEDGESHOW(Long value) {
        this.textedgeshow = value;
    }

    /**
     * Gets the value of the textlabelshow property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTLABELSHOW() {
        return textlabelshow;
    }

    /**
     * Sets the value of the textlabelshow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTLABELSHOW(Long value) {
        this.textlabelshow = value;
    }

    /**
     * Gets the value of the textlabelscale property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTLABELSCALE() {
        return textlabelscale;
    }

    /**
     * Sets the value of the textlabelscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTLABELSCALE(Long value) {
        this.textlabelscale = value;
    }

    /**
     * Gets the value of the textunderline property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTUNDERLINE() {
        return textunderline;
    }

    /**
     * Sets the value of the textunderline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTUNDERLINE(Long value) {
        this.textunderline = value;
    }

    /**
     * Gets the value of the textstrikethrough property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTSTRIKETHROUGH() {
        return textstrikethrough;
    }

    /**
     * Sets the value of the textstrikethrough property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTSTRIKETHROUGH(Long value) {
        this.textstrikethrough = value;
    }

    /**
     * Gets the value of the textheight property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTHEIGHT() {
        return textheight;
    }

    /**
     * Sets the value of the textheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTHEIGHT(Long value) {
        this.textheight = value;
    }

    /**
     * Gets the value of the textwidth property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTWIDTH() {
        return textwidth;
    }

    /**
     * Sets the value of the textwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTWIDTH(Long value) {
        this.textwidth = value;
    }

    /**
     * Gets the value of the textoffsetx property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTOFFSETX() {
        return textoffsetx;
    }

    /**
     * Sets the value of the textoffsetx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTOFFSETX(Long value) {
        this.textoffsetx = value;
    }

    /**
     * Gets the value of the textoffsety property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTOFFSETY() {
        return textoffsety;
    }

    /**
     * Sets the value of the textoffsety property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTOFFSETY(Long value) {
        this.textoffsety = value;
    }

    /**
     * Gets the value of the textalignment property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTALIGNMENT() {
        return textalignment;
    }

    /**
     * Sets the value of the textalignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTALIGNMENT(Long value) {
        this.textalignment = value;
    }

    /**
     * Gets the value of the textbackgroundshow property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTEXTBACKGROUNDSHOW() {
        return textbackgroundshow;
    }

    /**
     * Sets the value of the textbackgroundshow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTEXTBACKGROUNDSHOW(Long value) {
        this.textbackgroundshow = value;
    }

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFONT() {
        return font;
    }

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFONT(String value) {
        this.font = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMETADATA() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMETADATA(String value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the metadatatitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMETADATATITLE() {
        return metadatatitle;
    }

    /**
     * Sets the value of the metadatatitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMETADATATITLE(String value) {
        this.metadatatitle = value;
    }

    /**
     * Gets the value of the customindex property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCUSTOMINDEX() {
        return customindex;
    }

    /**
     * Sets the value of the customindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCUSTOMINDEX(Long value) {
        this.customindex = value;
    }

    /**
     * Gets the value of the customtooltip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTOMTOOLTIP() {
        return customtooltip;
    }

    /**
     * Sets the value of the customtooltip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTOMTOOLTIP(String value) {
        this.customtooltip = value;
    }

    /**
     * Gets the value of the rotation property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getROTATION() {
        return rotation;
    }

    /**
     * Sets the value of the rotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setROTATION(BigDecimal value) {
        this.rotation = value;
    }

    /**
     * Gets the value of the affiliation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAFFILIATION() {
        return affiliation;
    }

    /**
     * Sets the value of the affiliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAFFILIATION(String value) {
        this.affiliation = value;
    }

    /**
     * Gets the value of the urn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURN() {
        return urn;
    }

    /**
     * Sets the value of the urn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURN(String value) {
        this.urn = value;
    }

    /**
     * Gets the value of the tacticaldatatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTACTICALDATATYPE() {
        return tacticaldatatype;
    }

    /**
     * Sets the value of the tacticaldatatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTACTICALDATATYPE(String value) {
        this.tacticaldatatype = value;
    }

    /**
     * Gets the value of the timealertenabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTIMEALERTENABLED() {
        return timealertenabled;
    }

    /**
     * Sets the value of the timealertenabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTIMEALERTENABLED(Boolean value) {
        this.timealertenabled = value;
    }

    /**
     * Gets the value of the timealertmsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMEALERTMSG() {
        return timealertmsg;
    }

    /**
     * Sets the value of the timealertmsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMEALERTMSG(String value) {
        this.timealertmsg = value;
    }

    /**
     * Gets the value of the timealertdtg property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTIMEALERTDTG() {
        return timealertdtg;
    }

    /**
     * Sets the value of the timealertdtg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTIMEALERTDTG(Object value) {
        this.timealertdtg = value;
    }

    /**
     * Gets the value of the boundaryalertenterenabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBOUNDARYALERTENTERENABLED() {
        return boundaryalertenterenabled;
    }

    /**
     * Sets the value of the boundaryalertenterenabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBOUNDARYALERTENTERENABLED(Boolean value) {
        this.boundaryalertenterenabled = value;
    }

    /**
     * Gets the value of the startdisplaytime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSTARTDISPLAYTIME() {
        return startdisplaytime;
    }

    /**
     * Sets the value of the startdisplaytime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSTARTDISPLAYTIME(Long value) {
        this.startdisplaytime = value;
    }

    /**
     * Gets the value of the enddisplaytime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getENDDISPLAYTIME() {
        return enddisplaytime;
    }

    /**
     * Sets the value of the enddisplaytime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setENDDISPLAYTIME(Long value) {
        this.enddisplaytime = value;
    }

    /**
     * Gets the value of the enableonoffbydtg property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getENABLEONOFFBYDTG() {
        return enableonoffbydtg;
    }

    /**
     * Sets the value of the enableonoffbydtg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setENABLEONOFFBYDTG(Long value) {
        this.enableonoffbydtg = value;
    }

    /**
     * Gets the value of the modifiedtime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMODIFIEDTIME() {
        return modifiedtime;
    }

    /**
     * Sets the value of the modifiedtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMODIFIEDTIME(Integer value) {
        this.modifiedtime = value;
    }

    /**
     * Gets the value of the createtime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCREATETIME() {
        return createtime;
    }

    /**
     * Sets the value of the createtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCREATETIME(Integer value) {
        this.createtime = value;
    }

    /**
     * Gets the value of the w1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getW1() {
        return w1;
    }

    /**
     * Sets the value of the w1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setW1(String value) {
        this.w1 = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOURCE() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOURCE(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSIZE() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSIZE(BigDecimal value) {
        this.size = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the url property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getURL() {
        if (url == null) {
            url = new ArrayList<String>();
        }
        return this.url;
    }

    /**
     * Gets the value of the closed property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCLOSED() {
        return closed;
    }

    /**
     * Sets the value of the closed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCLOSED(Object value) {
        this.closed = value;
    }

    /**
     * Gets the value of the milplot property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMILPLOT() {
        return milplot;
    }

    /**
     * Sets the value of the milplot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMILPLOT(Integer value) {
        this.milplot = value;
    }

    /**
     * Gets the value of the mootwplot property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMOOTWPLOT() {
        return mootwplot;
    }

    /**
     * Sets the value of the mootwplot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMOOTWPLOT(Integer value) {
        this.mootwplot = value;
    }

    /**
     * Gets the value of the symbolfill property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSYMBOLFILL() {
        return symbolfill;
    }

    /**
     * Sets the value of the symbolfill property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSYMBOLFILL(Integer value) {
        this.symbolfill = value;
    }

    /**
     * Gets the value of the ntdsplotid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNTDSPLOTID() {
        return ntdsplotid;
    }

    /**
     * Sets the value of the ntdsplotid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNTDSPLOTID(Integer value) {
        this.ntdsplotid = value;
    }

    /**
     * Gets the value of the aa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAA() {
        return aa;
    }

    /**
     * Sets the value of the aa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAA(String value) {
        this.aa = value;
    }

    /**
     * Gets the value of the aavis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAAVIS() {
        return aavis;
    }

    /**
     * Sets the value of the aavis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAAVIS(Boolean value) {
        this.aavis = value;
    }

    /**
     * Gets the value of the abvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isABVIS() {
        return abvis;
    }

    /**
     * Sets the value of the abvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setABVIS(Boolean value) {
        this.abvis = value;
    }

    /**
     * Gets the value of the c property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getC() {
        return c;
    }

    /**
     * Sets the value of the c property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setC(BigInteger value) {
        this.c = value;
    }

    /**
     * Gets the value of the cvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCVIS() {
        return cvis;
    }

    /**
     * Sets the value of the cvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCVIS(Boolean value) {
        this.cvis = value;
    }

    /**
     * Gets the value of the dvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDVIS() {
        return dvis;
    }

    /**
     * Sets the value of the dvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDVIS(Boolean value) {
        this.dvis = value;
    }

    /**
     * Gets the value of the f property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getF() {
        return f;
    }

    /**
     * Sets the value of the f property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setF(Integer value) {
        this.f = value;
    }

    /**
     * Gets the value of the fvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFVIS() {
        return fvis;
    }

    /**
     * Sets the value of the fvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFVIS(Boolean value) {
        this.fvis = value;
    }

    /**
     * Gets the value of the g property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getG() {
        return g;
    }

    /**
     * Sets the value of the g property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setG(String value) {
        this.g = value;
    }

    /**
     * Gets the value of the gvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGVIS() {
        return gvis;
    }

    /**
     * Sets the value of the gvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGVIS(Boolean value) {
        this.gvis = value;
    }

    /**
     * Gets the value of the h property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getH() {
        return h;
    }

    /**
     * Sets the value of the h property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setH(String value) {
        this.h = value;
    }

    /**
     * Gets the value of the hvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHVIS() {
        return hvis;
    }

    /**
     * Sets the value of the hvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHVIS(Boolean value) {
        this.hvis = value;
    }

    /**
     * Gets the value of the h1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getH1() {
        return h1;
    }

    /**
     * Sets the value of the h1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setH1(String value) {
        this.h1 = value;
    }

    /**
     * Gets the value of the h1VIS property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isH1VIS() {
        return h1VIS;
    }

    /**
     * Sets the value of the h1VIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setH1VIS(Boolean value) {
        this.h1VIS = value;
    }

    /**
     * Gets the value of the h2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getH2() {
        return h2;
    }

    /**
     * Sets the value of the h2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setH2(String value) {
        this.h2 = value;
    }

    /**
     * Gets the value of the h2VIS property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isH2VIS() {
        return h2VIS;
    }

    /**
     * Sets the value of the h2VIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setH2VIS(Boolean value) {
        this.h2VIS = value;
    }

    /**
     * Gets the value of the j property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJ() {
        return j;
    }

    /**
     * Sets the value of the j property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJ(String value) {
        this.j = value;
    }

    /**
     * Gets the value of the jvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isJVIS() {
        return jvis;
    }

    /**
     * Sets the value of the jvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setJVIS(Boolean value) {
        this.jvis = value;
    }

    /**
     * Gets the value of the k property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getK() {
        return k;
    }

    /**
     * Sets the value of the k property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setK(String value) {
        this.k = value;
    }

    /**
     * Gets the value of the kvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKVIS() {
        return kvis;
    }

    /**
     * Sets the value of the kvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKVIS(Boolean value) {
        this.kvis = value;
    }

    /**
     * Gets the value of the l property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getL() {
        return l;
    }

    /**
     * Sets the value of the l property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setL(String value) {
        this.l = value;
    }

    /**
     * Gets the value of the lvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLVIS() {
        return lvis;
    }

    /**
     * Sets the value of the lvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLVIS(Boolean value) {
        this.lvis = value;
    }

    /**
     * Gets the value of the m property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getM() {
        return m;
    }

    /**
     * Sets the value of the m property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setM(String value) {
        this.m = value;
    }

    /**
     * Gets the value of the mvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMVIS() {
        return mvis;
    }

    /**
     * Sets the value of the mvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMVIS(Boolean value) {
        this.mvis = value;
    }

    /**
     * Gets the value of the n property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getN() {
        return n;
    }

    /**
     * Sets the value of the n property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setN(String value) {
        this.n = value;
    }

    /**
     * Gets the value of the nvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNVIS() {
        return nvis;
    }

    /**
     * Sets the value of the nvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNVIS(Boolean value) {
        this.nvis = value;
    }

    /**
     * Gets the value of the p property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getP() {
        return p;
    }

    /**
     * Sets the value of the p property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setP(String value) {
        this.p = value;
    }

    /**
     * Gets the value of the pvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPVIS() {
        return pvis;
    }

    /**
     * Sets the value of the pvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPVIS(Boolean value) {
        this.pvis = value;
    }

    /**
     * Gets the value of the svis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSVIS() {
        return svis;
    }

    /**
     * Sets the value of the svis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSVIS(Boolean value) {
        this.svis = value;
    }

    /**
     * Gets the value of the t property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getT() {
        return t;
    }

    /**
     * Sets the value of the t property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setT(String value) {
        this.t = value;
    }

    /**
     * Gets the value of the tvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTVIS() {
        return tvis;
    }

    /**
     * Sets the value of the tvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTVIS(Boolean value) {
        this.tvis = value;
    }

    /**
     * Gets the value of the v property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getV() {
        return v;
    }

    /**
     * Sets the value of the v property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setV(String value) {
        this.v = value;
    }

    /**
     * Gets the value of the vvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVVIS() {
        return vvis;
    }

    /**
     * Sets the value of the vvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVVIS(Boolean value) {
        this.vvis = value;
    }

    /**
     * Gets the value of the w property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getW() {
        return w;
    }

    /**
     * Sets the value of the w property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setW(String value) {
        this.w = value;
    }

    /**
     * Gets the value of the wvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWVIS() {
        return wvis;
    }

    /**
     * Sets the value of the wvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWVIS(Boolean value) {
        this.wvis = value;
    }

    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setX(BigDecimal value) {
        this.x = value;
    }

    /**
     * Gets the value of the xvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXVIS() {
        return xvis;
    }

    /**
     * Sets the value of the xvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXVIS(Boolean value) {
        this.xvis = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setY(String value) {
        this.y = value;
    }

    /**
     * Gets the value of the yvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isYVIS() {
        return yvis;
    }

    /**
     * Sets the value of the yvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setYVIS(Boolean value) {
        this.yvis = value;
    }

    /**
     * Gets the value of the z property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getZ() {
        return z;
    }

    /**
     * Sets the value of the z property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setZ(BigDecimal value) {
        this.z = value;
    }

    /**
     * Gets the value of the zvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isZVIS() {
        return zvis;
    }

    /**
     * Sets the value of the zvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setZVIS(Boolean value) {
        this.zvis = value;
    }

    /**
     * Gets the value of the q property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQ() {
        return q;
    }

    /**
     * Sets the value of the q property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQ(BigDecimal value) {
        this.q = value;
    }

    /**
     * Gets the value of the qvis property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getQVIS() {
        return qvis;
    }

    /**
     * Sets the value of the qvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setQVIS(Object value) {
        this.qvis = value;
    }

    /**
     * Gets the value of the evis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEVIS() {
        return evis;
    }

    /**
     * Sets the value of the evis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEVIS(Boolean value) {
        this.evis = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the position property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPOSITION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getPOSITION() {
        if (position == null) {
            position = new ArrayList<BigDecimal>();
        }
        return this.position;
    }

    /**
     * Gets the value of the framefillvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFRAMEFILLVIS() {
        return framefillvis;
    }

    /**
     * Sets the value of the framefillvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFRAMEFILLVIS(Boolean value) {
        this.framefillvis = value;
    }

    /**
     * Gets the value of the optframevis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOPTFRAMEVIS() {
        return optframevis;
    }

    /**
     * Sets the value of the optframevis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOPTFRAMEVIS(Boolean value) {
        this.optframevis = value;
    }

    /**
     * Gets the value of the roleiconvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isROLEICONVIS() {
        return roleiconvis;
    }

    /**
     * Sets the value of the roleiconvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setROLEICONVIS(Boolean value) {
        this.roleiconvis = value;
    }

    /**
     * Gets the value of the spdldrvis property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSPDLDRVIS() {
        return spdldrvis;
    }

    /**
     * Sets the value of the spdldrvis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSPDLDRVIS(Boolean value) {
        this.spdldrvis = value;
    }

}
